### ISSUE TITLE
x201 Tablet PC Does Not Recognize Serial Device [ArchLinux]

### ISSUE THREAD

**Issue by Ellicit** [linuxwacom/input-wacom#106]
Right, so, I've been loaned a Lenovo x201 Thinkpad with a touchscreen that, as far as I know, was more or less functioning before it was wiped to run first Ubuntu (by the previous user) and then ArchLinux (by me). Currently, while the screen functions as a monitor, I can't seem to get it to believe that it's also a Wacom device:
 
> $ lsusb
> Bus 002 Device 002: ID 8087:0020 Intel Corp. Integrated Rate Matching Hub
> Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 001 Device 005: ID 17ef:4816 Lenovo Integrated Webcam
> Bus 001 Device 004: ID 147e:2016 Upek Biometric Touchchip/Touchstrip Fingerprint Sensor
> Bus 001 Device 003: ID 046d:c52f Logitech, Inc. Unifying Receiver
> Bus 001 Device 002: ID 8087:0020 Intel Corp. Integrated Rate Matching Hub
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```
$ lspci
00:00.0 Host bridge: Intel Corporation Core Processor DRAM Controller (rev 02)
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 02)
00:16.0 Communication controller: Intel Corporation 5 Series/3400 Series Chipset HECI Controller (rev 06)
00:16.3 Serial controller: Intel Corporation 5 Series/3400 Series Chipset KT Controller (rev 06)
00:19.0 Ethernet controller: Intel Corporation 82577LM Gigabit Network Connection (rev 06)
00:1a.0 USB controller: Intel Corporation 5 Series/3400 Series Chipset USB2 Enhanced Host Controller (rev 06)
00:1b.0 Audio device: Intel Corporation 5 Series/3400 Series Chipset High Definition Audio (rev 06)
00:1c.0 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 1 (rev 06)
00:1c.3 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 4 (rev 06)
00:1c.4 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 5 (rev 06)
00:1d.0 USB controller: Intel Corporation 5 Series/3400 Series Chipset USB2 Enhanced Host Controller (rev 06)
00:1e.0 PCI bridge: Intel Corporation 82801 Mobile PCI Bridge (rev a6)
00:1f.0 ISA bridge: Intel Corporation QM57 Chipset LPC Interface Controller (rev 06)
00:1f.2 IDE interface: Intel Corporation 5 Series/3400 Series Chipset 4 port SATA IDE Controller (rev 06)
00:1f.3 SMBus: Intel Corporation 5 Series/3400 Series Chipset SMBus Controller (rev 06)
00:1f.5 IDE interface: Intel Corporation 5 Series/3400 Series Chipset 2 port SATA IDE Controller (rev 06)
00:1f.6 Signal processing controller: Intel Corporation 5 Series/3400 Series Chipset Thermal Subsystem (rev 06)
02:00.0 Network controller: Intel Corporation Centrino Advanced-N 6200 (rev 35)
ff:00.0 Host bridge: Intel Corporation Core Processor QuickPath Architecture Generic Non-core Registers (rev 02)
ff:00.1 Host bridge: Intel Corporation Core Processor QuickPath Architecture System Address Decoder (rev 02)
ff:02.0 Host bridge: Intel Corporation Core Processor QPI Link 0 (rev 02)
ff:02.1 Host bridge: Intel Corporation 1st Generation Core i3/5/7 Processor QPI Physical 0 (rev 02)
ff:02.2 Host bridge: Intel Corporation 1st Generation Core i3/5/7 Processor Reserved (rev 02)
ff:02.3 Host bridge: Intel Corporation 1st Generation Core i3/5/7 Processor Reserved (rev 02)
```

Using dmesg | grep wacom before trying to reload any modules returns exactly one line:
`[    7.738103] audit: type=1131 audit(1565823865.339:25): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=wacom-inputattach@ttyS0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'`

There's nothing labeled "wacom" in /proc/bus/input/devices, either; this all led me to believe that this was a driver issue, as per the [ArchLinux wiki page for Wacom](https://wiki.archlinux.org/index.php/Wacom_tablet), so for a while I've been proceeding under that assumption. IInitially `sudo inputattach -w8001 /dev/ttyS0` was throwing errors, which went away when I built and installed the input-wacom package from source. Now it just hangs with no output. Using isdv4-serial-inputattach gets some actual output:
```
' $ sudo isdv4-serial-inputattach --verbose /dev/ttyS0
... Opening device '/dev/ttyS0'.
... Baud rate is 38400
... Querying tablet.
... Writing STOP command.
... Written '0'.
... Written '*'.
timeout.
error during query.
... Waiting for tablet...Initial tablet query failed. Trying with baud rate 19200.
... Baud rate is 19200
... Querying tablet.
... Writing STOP command.
... Written '0'.
... Written '*'.
timeout.
error during query.
Tablet query failed, cannot initialize.
... Waiting for tablet...%'
```

[This forum thread](https://bbs.archlinux.org/viewtopic.php?id=185173) seems to involve a similar issue, but has evidence of the tablet actually existing. Is there anything else I can and should do to diagnose/fix this, or is this a project better left incomplete?

**Comment by jigpu** [comment]
Serial devices can be pretty difficult to get running. You might try testing other serial devices (e.g. /dev/ttyS1, etc.) since the tablet may not always be on the first port. I remember one HP device, at least, that had it at /dev/ttyS4 for whatever reason.

If none of the serial devices respond, another option could be trying to communicate at 9600 baud. I believe some devices will at least identify themselves at this rate, though I'm not sure if that's enough bandwidth for them to actually work well. You should be able to add `--baudrate 9600` to your isdv4-serial-inputattach command to achieve this.

If even that doesn't work, you might try running the `isdv4-serial-debugger` command. Its a long-shot since its basically the same code as isdv4-serial-inputattach, but maybe it would be able to start communicating with the device...
