### ISSUE TITLE
input-wacom compilation failure on install

### ISSUE THREAD

**Issue by restagner** [linuxwacom/input-wacom#113]
I've just install a fresh copy of Kubuntu 18.04.3 (Kernel: 4.15.0-58-generic).  When I attempt to run

```bash
if test -x ./autogen.sh; then ./autogen.sh; else ./configure; fi && make && sudo make install || echo "Build Failed"
```

from within the **input-wacom-0.43.0** directory, I receive the following error.  Any idea on how to correct this error?

```
/bin/sh: 1: cannot create /home/restagner/Wacom/.cache.mk: Directory nonexistent
arch/x86/Makefile:245: *** You are building kernel with non-retpoline compiler, please update your compiler..  Stop.
make[3]: Leaving directory '/usr/src/linux-headers-4.15.0-58-generic'
Makefile:39: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/restagner/Wacom for Linux/input-wacom-0.43.0/4.5'
Makefile:377: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/restagner/Wacom for Linux/input-wacom-0.43.0'
Makefile:308: recipe for target 'all' failed
make: *** [all] Error 2
Build Failed
```

The following packages are already installed

```
$ dpkg --get-selections | ack wacom
libwacom-bin                                    install
libwacom-common                                 install
libwacom2:amd64                                 install
xserver-xorg-input-wacom                        install
```

**Comment by jigpu** [comment]
It looks like Kubuntu may be shipping a version of the GCC compiler which doesn't have the new "retpoline" fixes that recent kernels require. I believe you should be able to run `sudo apt-get install gcc-8` to install a newer version, and then follow the instructions at https://askubuntu.com/a/1028656 to use the `update-alternatives` command to make GCC 8 the default. Afterwards, try running the build command again.
