### ISSUE TITLE
Kernel crashes if I draw on the screen with the pen during wake-up from suspend on X200T

### ISSUE THREAD

**Issue by Akraboy** [linuxwacom/input-wacom#131]
This issue is a follow-up to another issue (https://github.com/linuxwacom/xf86-input-wacom/issues/86) where this new problem was already mentioned. I will explain it again here:

If I wake my ThinkPad X200T from suspend and at the same time draw on the screen with the pen there is a chance that the system will crash.

This can be avoided by not drawing on the screen during the wake-up period.

This [journal log](https://github.com/linuxwacom/xf86-input-wacom/files/3739982/journal_crash.txt) is from the previously mentioned issue (https://github.com/linuxwacom/xf86-input-wacom/issues/86).

**Comment by Pinglinux** [comment]
The device is more than 10-years old. We recommend the workaround (don't do it).
