### ISSUE TITLE
How to get Intuos4 OLED working?

### ISSUE THREAD

**Issue by willRo444** [linuxwacom/input-wacom#142]
Hi,

I would like to use the OLED screens on my intuos4 M, but there is no option to activate it (using manjaro kde, installed kcm-wacomtablet  1:3.2.0-3 (xf86-input-wacom  0.38.0-1, libwacom  1.1-1)).

On https://wiki.archlinux.org/index.php/Wacom_tablet it says to edit /etc/udev/rules.d/99-wacom.rules but that file does not exist and to install i4oled (AUR) but that repo (https://github.com/PrzemoF/i4oled or https://github.com/PrzemoF/i4oled-gui) does no longer exist. 

Is it supposed to work at all?

**Comment by Pinglinux** [comment]
We worked on OLED a while back, more than 10 years ago, around 2009. Once the feature was integrated into Gnome, we relied on Gnome. Intuos4 OLED were mentioned at a few places:

https://github.com/sanette/intuos4-oled (project looks like an active one. Last commit was Oct 2021);
https://github.com/linuxwacom/input-wacom/issues/81 (/sys/bus/hid/drivers/wacom/0003\:056A\:00BC.0001/wacom_led is where you access the oled);
https://sourceforge.net/p/linuxwacom/mailman/linuxwacom-discuss/thread/167e8a331002040944t4c737477n1e8329aa698617f2%40mail.gmail.com

That's all I can find online...
