### ISSUE TITLE
Build Failed - Kernel doesn't have the configuration files

### ISSUE THREAD

**Issue by Twiggeh** [linuxwacom/input-wacom#153]
Terminal Dump :

```
[twiggeh@Twiggeh-Linux input-wacom-0.45.0]$ if test -x ./autogen.sh; then ./autogen.sh; else ./configure; fi && make && sudo make install || echo "Build Failed"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... none
checking if build path '/home/twiggeh/Downloads/input-wacom-0.45.0' has spaces... no
checking for kernel type... Linux
checking for linux-based kernel... yes
checking for kernel source/headers... not found
configure: WARNING: Unable to find build config in any of:
	  [/lib/modules/5.6.0-2-MANJARO/source],
	  [/lib/modules/5.6.0-2-MANJARO/build],
	  [/usr/src/linux],
	  [/usr/src/linux-5.6.0-2-MANJARO],
	  [/usr/src/linux-2.6]
	

configure: WARNING: Kernel directory does not appear to have needed config files
checking kernel version... 
configure: WARNING: Spcified '5.6.0-2-MANJARO' kernel, but found '' instead
configure: error: We could not find the development environment to build modules for the '5.6.0-2-MANJARO' kernel within the '' directory. Please install the kernel source or the kernel development package and try again.
Build Failed
```

I ran `sudo pacman -S base-devel linux-headers` after the manjaro installation & rebooted my pc. Rebooting multiple times didn't fix the issue :(
The issue I'm trying to fix is that when I use my Cintiq 13hd the pen surface gets stretched to both of my displays (the cintiq and my monitor). Discord screenshare also sees both monitors as one monitor, so that might be the issue as well. 
Also I don't have any way of configuring the tablet. `xsetwacom list dev` returns nothing.

**Comment by jigpu** [comment]
Your issue of the Cintiq being stretched to both displays won't be fixed by a kernel driver update. The display mapping is entirely controlled by userspace. If you are using GNOME or Cinnamon, it should automatically map the Cintiq correctly. If you are using any other desktop you will need to use the "MapToOutput" option of xsetwacom to map the pen to the correct display. What desktop environment are you using?

For the build issue: can you provide the output from `ls /lib/modules` and `uname -r` please?

For the xsetwacom issue: can you provide the output from `echo $XDG_SESSION_TYPE` please?

**Comment by Twiggeh** [comment]
Hi ! 
I'm using xfce, and I tried reinstalling the driver because `xsetwacom --list devices` returned nothing. I have no idea why, but it started working and I could remap my output by using `xsetwacom set "Wacom Cintiq 13HD Pen stylus" MapToOutput "HEADER-0"`, so that resolved my issue :) 

I did not continue trying to build the drivers, but here are the outputs that you asked for :

ls /lib/modules : 
```
3.16.82-2-MANJARO
5.6.0-2-MANJARO
extramodules-5.6-MANJARO
4.14.171-1-MANJARO
extramodules-4.14-MANJARO
```
uname -r
```
5.6.0-2-MANJARO
```
echo $XDG_SESSION_TYPE 
```
x11
```
Interestingly enough a new issue arose. Drawing a line doesn't result in a continuous line, but sometimes the stroke disconnects as if I've lifted the pen. Would you know how to troubleshoot that ? ![Image](https://imgur.com/PDYRVQO.png)

Thank you so much for your help so far and please tell me if I should try building the drivers if that is of any value to you :)
