### ISSUE TITLE
Is there support for Cintiq ID 056a:00f9

### ISSUE THREAD

**Issue by hoyanf** [linuxwacom/input-wacom#154]
Hi, 
I'm just wondering if there is official support for Wacom Cintiq with USB ID 056A:00F9.

dmesg.log

```
[23295.961121] usb 4-1.6.2.3.2.2: new high-speed USB device number 104 using ehci-pci
[23296.068337] usb 4-1.6.2.3.2.2: New USB device found, idVendor=056a, idProduct=00f9
[23296.068342] usb 4-1.6.2.3.2.2: New USB device strings: Mfr=10, Product=11, SerialNumber=0
[23296.068345] usb 4-1.6.2.3.2.2: Product: Cintiq 22HD HUB
[23296.068347] usb 4-1.6.2.3.2.2: Manufacturer: WACOM
[23296.068833] hub 4-1.6.2.3.2.2:1.0: Unsupported bus topology: hub nested too deep
[23296.068840] hub: probe of 4-1.6.2.3.2.2:1.0 failed with error -7
```

host details
```
Linux HOSTNAME 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core
```

Thanks

**Comment by jigpu** [comment]
056a:00f9 is a USB hub and I believe should work fine. I'm not aware of anything special about this particular device. The "hub nested too deep" error that you see is due to the Cintiq being connected through too many layers of USB hubs. Try connecting the Cintiq to a different USB port, ideally one directly on the system itself.

**Comment by hoyanf** [comment]
![linux-usbids-cintiq](https://user-images.githubusercontent.com/15434685/75945973-b7ed0e80-5ed6-11ea-8763-ec55428eac91.png)
The reason am asking because the device id is not within the one listed as supported.

Thanks

**Comment by jigpu** [comment]
The "usb.ids" list is only used to provide "friendly" device names in programs like `lsusb`. It is in no way a list of supported devices, or has any impact on if a device will work. Many tablet PC sensors, for instance, have not been added to the list (new ones keep popping up all the time, and we aren't notified about most of them...)

I've just added the device to the list anyway, and it should be showing up in the future. Note that it can take weeks or months for updates to the list to roll out...
