### ISSUE TITLE
Pan options in UI

### ISSUE THREAD

**Issue by mateMathieu** [linuxwacom/input-wacom#156]
Hello,
Thanks for the great piece of software, a pleasure to use this tablet on Linux.

I figured there is no option to use a pan function on Linux to facilitate navigation and use of the tablet on the desktop.
After digging a little, I came across the two following commands to help use this tablet on a general desktop use. I need to use those every time I start using this tablet.

```
xsetwacom --set "Wacom Intuos BT M Pen stylus" Button 2 "pan"
xsetwacom --set "Wacom Intuos BT M Pen stylus" "PanScrollThreshold" 200
```
Can you implement these functions through graphical interface? That would help people stick to Linux and your driver.
Regards

**Comment by jigpu** [comment]
We do not maintain any of the graphical tablet configuration tools. I would recommend opening a feature request for either the  [GNOME Control Center](https://gitlab.gnome.org/GNOME/gnome-control-center/issues) (for GNOME, Cinnamon, etc. environments) or the [KDE Wacom Tablet module](https://bugs.kde.org/enter_bug.cgi?product=wacomtablet) depending on which environment you use.
