### ISSUE TITLE
 can not use wacom pth660 on Ubuntu buidge 17.04 only connection succeed

### ISSUE THREAD

**Issue by 243750496** [linuxwacom/input-wacom#16]
![screenshot](https://cloud.githubusercontent.com/assets/6311930/24926802/68439532-1f2f-11e7-8619-71178215aac1.png)
![screenshot-wacom](https://cloud.githubusercontent.com/assets/6311930/24926864/a3e266c2-1f2f-11e7-8866-d21f8690f6e2.png)

with the pen moved there's nothing happened and theres no item show up in wacom settings page
so any solutions?

BTW:xserver-xorg-input-wacom=0.34
![version](https://cloud.githubusercontent.com/assets/6311930/24927003/127976fc-1f30-11e7-8d27-724d783b44ca.png)

**Comment by skomra** [comment]
For support of the second generation Intuos Pro you will eventually depend on kernel 4.11 or later (currently 4.11 is in rc releases). You will be better off installing input-wacom 0.35.0. (xserver-xorg-input-wacom is necessary but unrelated to your current problem.)

You will also need to install an updated libwacom for the control panel (second screen shot) to display the device.

 Instructions for installing the input-wacom and libwacom are available at http://linuxwacom.sourceforge.net/wiki/index.php/Downloads

**Comment by jigpu** [comment]
Closing since support for this device is already available in input-wacom.
