### ISSUE TITLE
Request: GUI Option for Scroll-by-Grab

### ISSUE THREAD

**Issue by labor4** [linuxwacom/input-wacom#165]
Hi
I'd like to know if this **idea** should/would be integrated in the Gnome settings.
(I hope this is the right place to ask)

I want to scroll a page/folder/etc by  grabbing/using one of the pen's buttons.
Currently I use an ugly hook into udev and let it inject the change into the session of 1 user, to maintain functionality whenever the Wacom tablet is reconnected (which it often does in my case of using KVMoverIP).

I wish you would evaluate the benefit and maybe hopefully integrate **a real solution for it** into standard functionality via GUI.

My current weirdness to workaround it is:
```
#!/bin/bash
# this is file /home/tools/wacomfix.sh
# https://unix.stackexchange.com/questions/65788/why-doesnt-xsetwacom-work-from-udev

ROOTDOESTHISUSER=supermario

function delayset (){
	
	THISHOME=$1
	set > $THISHOME/Desktop/wacomfix_pending
	sleep 3

	/usr/bin/xsetwacom set "Wacom Intuos Pro M Pen stylus" Button 3 pan &>/dev/null
	/usr/bin/xsetwacom set "Wacom Intuos Pro M Pen stylus" PanScrollThreshold 300 &>>/dev/null
	/usr/bin/xsetwacom --set $(xsetwacom --list | grep TOUCH | sed "s/.*id:\s\([[:digit:]]*\).*/\1/g") touch off	
	sleep 2
	rm -f $THISHOME/Desktop/wacomfix_pending
}
export -f delayset


if [ "$EUID" -eq 0 ];then


	su $ROOTDOESTHISUSER<<'OLLA'


	#export XAUTHORITY=$HOME/.Xauthority
	export XAUTHORITY=/run/user/$(id -u $ROOTDOESTHISUSER)/gdm/Xauthority
	export DISPLAY=:0



	nohup bash -c "delayset $HOME" >/dev/null 2>&1 & 
	#nohup su -c "delayset $HOME" $ROOTDOESTHISUSER >/dev/null 2>&1 & 
OLLA

else
	nohup bash -c "delayset $HOME" >/dev/null 2>&1 & 

fi




exit 


# Install udev rule
cat > /etc/udev/rules.d/80-mywacomfix.rules<<EOF
SUBSYSTEMS=="usb", ACTION=="add", ATTRS{idVendor}=="056a", ATTRS{idProduct}=="0315", RUN+="/home/tools/wacomfix.sh" 
EOF
udevadm control --reload-rules


```

**Comment by jigpu** [comment]
We don't directly control what gets into GNOME, so you'll want to file an issue with them. The place to go is https://gitlab.gnome.org/GNOME/gnome-control-center/issues

I agree this would be nice though. Its possible their experience could be even better than what is offered by xsetwacom too. They already support smooth scrolling by finger drag for touchscreens, and if they could hook that same feature up to the pen+button (when configured to do so), it could be pretty nice.
