### ISSUE TITLE
Bamboo Slate

### ISSUE THREAD

**Issue by karlkappe** [linuxwacom/input-wacom#168]
As recommended by @jigpu I will open a new issue. I am trying to set up the bamboo slate on Mint 18.03. I was able to install input-wacom vers 0.43 to vers 0.44. I updated xf86-input-wacom and installed libvacom from source (this was a bit tricky).
When a make `modinfo wacom | grep version` I get
```
version:        v2.00-0.43.0
srcversion:     80DFFC369A4B8AB3E691E47
```
But when I try to pair the device via bluetooth it fails.
I try 
```
bluetoothctl
agent on
scan on

```
I can see Device FB:8C:DB:1D:59:7B Bamboo Slate then
```
scan off
pair FB:8C:DB:1D:59:7B 

```
Now the part that is not working
```
[CHG] Device FB:8C:DB:1D:59:7B Connected: yes
[Bamboo Slate]# connect FB:8C:DB:1D:59:7B 
[CHG] Device FB:8C:DB:1D:59:7B Connected: yes
[Bamboo Slate]# connect FB:8C:DB:1D:59:7B 
Attempting to connect to FB:8C:DB:1D:59:7B
Connection successful
[Bamboo Slate]# info FB:8C:DB:1D:59:7B
Device FB:8C:DB:1D:59:7B
	Name: Bamboo Slate
	Alias: Bamboo Slate
	Paired: no
	Trusted: yes
	Blocked: no
	Connected: yes
	LegacyPairing: no
	UUID: Vendor specific           (00001523-1212-efde-1523-785feabcd123)
	UUID: Vendor specific           (00001530-1212-efde-1523-785feabcd123)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
	UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (3a340720-c572-11e5-86c5-0002a5d5c51b)
	UUID: Vendor specific           (6e400001-b5a3-f393-e0a9-e50e24dcca9e)
	UUID: Vendor specific           (ffee0001-bbaa-9988-7766-554433221100)
	Modalias: usb:v056Ap0329d0001
[CHG] Device FB:8C:DB:1D:59:7B Connected: no
Failed to pair: org.bluez.Error.AuthenticationCanceled
```
And now I am lost. My other bluetooth devices work fine so I do not think it is a bluetooth problem.

**Comment by jigpu** [comment]
I believe the Bamboo Slate uses a Bluetooth LE connection rather than standard Bluetooth pairing. You'll need to use something like [Tuhi](https://github.com/tuhiproject/tuhi) to connect to and download images from the device. The [Bamboo Spark documentation](https://github.com/tuhiproject/tuhi#device-notes) should apply to your Bamboo Slate as well.

Let me know if that helps or not...
