### ISSUE TITLE
Kubuntu 20.04 - Wacom issues 

### ISSUE THREAD

**Issue by anand-coding** [linuxwacom/input-wacom#171]
Tablet: https://www.amazon.ca/gp/product/B010LHRFM2
Issue: Some clicks do not work
1. Installed Virtual box (6.1 from default repo). I cannot click on the menu bar or start a virtual machine. The title bar clicks work fine.
2. Super + q. Then click the activities settings module. Title bar clicks work. But, if I click anywhere else on the screen (Activities, switching, privacy), it does not work.

**Comment by jigpu** [comment]
Please see https://github.com/linuxwacom/xf86-input-wacom/wiki/Known-Issues#qt-offset-bug
