### ISSUE TITLE
Ubuntu 20.04 Touchpad (Relative) Mode is Glitchy

### ISSUE THREAD

**Issue by bxbrenden** [linuxwacom/input-wacom#176]
## Issue Description
Wacom Intuos Pro M stylus is not working properly when set to `Touchpad (Relative)` mode in the `Wacom Tablet` settings on Ubuntu 20.04.

## Details
I just upgraded my OS to the stock installation of Ubuntu 20.04 Focal Fossa. My Wacom tablet works out of the box because Ubuntu 20.04 comes preinstalled with various`linuxwacom` software (listed below in detail). However, only the `Tablet (Absolute)` mode in the settings works properly. 

When I change the mode to `Touchpad (Relative)`, the stylus must be placed extremely close to the tablet in order to register a mouse movement. Even when it moves the cursor, the input sampling is very jumpy / spotty. A continuous hand gesture will not produce a continuous stylus stroke; it lags, jumps, and some cases stops moving all together.

I also compiled and installed the latest version of `input-wacom` from source using the [documentation](https://github.com/linuxwacom/input-wacom/wiki/Installing-input-wacom-from-source) in the `input-wacom` wiki. Even with the very newest version of the `wacom` kernel module the issue still persists.

The wiki also [suggests](https://github.com/linuxwacom/xf86-input-wacom/wiki/Building-The-Driver) building the `xf86-input-wacom` from source and installing it, but Ubuntu 20.04 already has the latest release of this, so I did not try.

## Steps to Reproduce
1. Install stock installation of Ubuntu 20.04 Focal Fossa
2. Plug in an Intuos Pro M pad
3. Move the cursor with the Intuos Pro stylus to verify that it works in the default mode of `Tablet (Absolute)`.
4. In the Gnome desktop go to `Settings -> Wacom Tablet` and click on the `Tablet` tab.
5. Change the `Tracking Mode` from `Tablet (Absolute)` to `Touchpad (Relative)`.
6. Repeat step 3. You should notice a more jittery experience, and the stylus will have to be very close to the pad to move the mouse cursor.

### Software installed on Ubuntu:
| Package Name | Version |
|----------------------|-----------:|
| xserver-xorg-input-wacom | 0.39.0-0ubuntu1|
| libwacom-bin | 1.3-2ubuntu1|
| libwacom-common | 1.3-2ubuntu1|
| libwacom2:amd64 | 1.3-2ubuntu1|

### Version of Wacom Kernel Module
```bash
user@machine$: $ modinfo wacom | grep version
version:        v2.00-0.45.0
srcversion:     0AA19FE5A3E9C50CD127943
```

### Wacom Tablet Versions Affected
I tested with the following two Wacom tablets:
`Wacom Intuos Pro M Pen / Stylus`
`Wacom Intuos CTL 4100 Pen / Stylus`

**Comment by jigpu** [comment]
You will want to adjust the "CursorProximity" setting for your stylus tool to change the maximum allowed hover height. Different people raise the pen different amounts when re-positioning in relative mode, and it sounds like the default isn't comfortable for you.

You can run `xsetwacom set <stylus> CursorProximity <distance>` with a distance value between 0 and 63 to adjust the maximum hover distance. Lower values have reduced hover distance, higher values will increase it (up to the hardware maximum, of course). Once you've found a hover height that works well for you, you can create an [xorg.conf.d configuration file](https://github.com/linuxwacom/xf86-input-wacom/wiki/xorg.conf.d#example-configuration) with an `Option "CursorProx" "<distance>"` line in it to persist the setting across reboots.
