### ISSUE TITLE
input wacom issues with intous4 wacoms on hardware vs vm

### ISSUE THREAD

**Issue by rareshornet** [linuxwacom/input-wacom#19]
Hi guys,

We have some issues with the newest drivers. We use multiple wacoms, PTH-660(Pro 2), PTK-640 (Intuos4) and PTH-651(Intuso 5).The intuos 5 and Pro2 work fine with 0.37.1 release but the Intuos4 pen doesn't want to produce any input unless i manually remove the kernel module and reinsert it back using modprobe -r/i wacom.When i connect the tablet it gets detected by the kernel and the wacom module get loaded automatically. Even the kcmwacomtabled kde module will find it and display a message on the screen that's its been detected but the pen doesn't move and only the express buttons would work. I tested on a clean centos 7 latest install and its reproducible on large hardware range but not on a VM. If I test with a VM in virtual box there are no driver issues at all, Intuos4 would work properly every time.I also tried to downgrade a few versions and the only way I got to get the intuos4 tables was with 0.35.0 but then the the Pro 2 wacoms don't work anymore :(

Any help would be very much appreciated. 

Thanks!
--

**Comment by Pinglinux** [comment]
Can not be reproduced
