### ISSUE TITLE
Bluetooth not working after rebooting machine

### ISSUE THREAD

**Issue by demba** [linuxwacom/input-wacom#204]
Thanks for putting this project together.

I have been using the Wacom Intuos M tablet with Ubuntu 16.04. At first, I could only use the tablet when connecting via USB: BT was not working. After installing input-wacom, I got BT to work. However, after restarting my laptop, BT stopped working. USB still works.

I followed the instructions under "Troubleshooting" w/o any success.

Note that `grep "" /sys/module/wacom*/version` yields `v2.00`.

Thanks in advance.

**Comment by Pinglinux** [comment]
Did you try to reinstall wacom.ko from input-wacom? The driver could have been removed by an update or another app...

**Comment by Pinglinux** [comment]
v2.00 is the in-box driver. To use the latest wacom.ko, you'll need to install it to Ubuntu 16.04 or upgrade to the latest Ubuntu version.
