### ISSUE TITLE
pen gets mapped to the wrong display

### ISSUE THREAD

**Issue by AndrewLyasoff** [linuxwacom/input-wacom#210]
After the recent upgrade to kernel 5.8.15-201.fc32.x86_64 on Fedora 32, the pen appears to get mapped not on the Wacom tablet (Wacom One) but on another display. The issue occurs if the tablet is unplugged and then plugged back in without rebooting, and cannot be resolved from within the Wacom Tablet settings in the gnome-control-center. The only workaround at this point -- other than rebooting with the tablet plugged in -- appears to be explicitly mapping the pen from the terminal with 'xsetwacom --set ...' There were no such issues until kernel 5.8.13-200.fc32.x86_64, but rebooting with that kernel after the latest f32 upgrade does not resolve the problem -- even if one restores the kernel-devel for 5.8.13-200.fc32.x86_64.

**Comment by Pinglinux** [comment]
This is not a kernel driver issue. If it is not something in libwacom, it would most likely in Gnome-control-center.
