### ISSUE TITLE
Arch Linux, One by Wacom Medium (CTL-672-N) Can't get it working

### ISSUE THREAD

**Issue by ondersumer07** [linuxwacom/input-wacom#211]
Hello, I am using a Lenovo Thinkpad X250 with Arch Linux. I've tried to install input-wacom in order to have tablet support. First I assured that I have the prerequisites. Then I downloaded the package and copy and pasted the command below. Anyways when I run it, I get "Build Failed" message. I am not an expert on Arch Linux but I would love to have tablet support on my laptop. It actually sucks that Wacom does not develop drivers for linux. Thank you for the project anyways and hope we can fix this issue. Have a nice one1

**Comment by ondersumer07** [comment]
Error code:
```
WARNING: Spcified '5.8.13-arch1-1' kernel, but found '5.9.1-arch1-1' instead
configure: error: We could not find the development environment to build modules for the '5.8.13-arch1-1' kernel within the '/usr/src/linux' directory. Please install the kernel source or the kernel development package and try again.
Build Failed
```

**Comment by Pinglinux** [comment]
> Hello, I am using a Lenovo Thinkpad X250 with Arch Linux. I've tried to install input-wacom in order to have tablet support. First I assured that I have the prerequisites. Then I downloaded the package and copy and pasted the command below. Anyways when I run it, I get "Build Failed" message. I am not an expert on Arch Linux but I would love to have tablet support on my laptop. It actually sucks that Wacom does not develop drivers for linux. Thank you for the project anyways and hope we can fix this issue. Have a nice one1

"**First I assured that I have the prerequisites**"  -- We can't assume much in tech world ;). We have to make sure your system meets the prerequisites;
"**I am not an expert on Arch Linux**"  -- There is no need to be an expert to compile and install the driver. We just need to follow the steps, one step at a time;
"**It actually sucks that Wacom does not develop drivers for linux**."  -- The fact is that there are four WACOM paid open source developers, including myself, behind this project.

If you don't feel comfortable to compile and install the driver on an older Linux system, your best bet is to always upgrade your system to the latest version, especially for the kernel.
