### ISSUE TITLE
Wacom pen pressure is not workling on centos 7

### ISSUE THREAD

**Issue by pravinrupnoor** [linuxwacom/input-wacom#212]
Hello,

I have installed wacom xf86-input-wacom-0.36.0 & input-wacom-0.46.0 in Centos 7,but still wacom pressure is not working.
Wacom intous 3 
VEIKK s640.

Please give me solution ASAP.

Regard's,
Pravin Rupnoor.

**Comment by jigpu** [comment]
Hi, please run our [sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) and attach the generated tarball here.

**Comment by Pinglinux** [comment]
It's been more than a year without a reply. I assume the issue has been resolved.
