### ISSUE TITLE
Wacom One compatible?

### ISSUE THREAD

**Issue by juliengmt-4** [linuxwacom/input-wacom#226]
Hello,
Is your project compatible with the Wacom One? I have a Rapberry Pi 4, 2GB Ram, and I would like to upgrade from my old Wacom Intuos to a Tablet Display, and I’m hesitating between the One, the XP-Pen Artist and the Huion Kamvas.

Thanks!

**Comment by jigpu** [comment]
Yes, we support both the Wacom One and the Raspberry Pi. The device may or may not work out of the box depending on the exact OS that you install onto the Pi, but the [input-wacom install instructions](https://github.com/linuxwacom/input-wacom/wiki/Installing-input-wacom-from-source) should get you up and running even if not. If you have any trouble using the two together, let us know.
