### ISSUE TITLE
gmail mis-detects url in ANNOUNCE email 

### ISSUE THREAD

**Issue by skomra** [linuxwacom/input-wacom#24]
Gmail detects the release url from the .announce email as (for example)

https://github.com/linuxwacom/input-wacom/releases/download/input-wacom-0.39.0/input-wacom-0.39.0.tar.bz2MD5

instead of

https://github.com/linuxwacom/input-wacom/releases/download/input-wacom-0.39.0/input-wacom-0.39.0.tar.bz2

https://sourceforge.net/p/linuxwacom/mailman/message/36268424/

This bug also applies to xf86-input-wacom

**Comment by jigpu** [comment]
Fixed by 6cba8dade289e4160df5b1fae4da81da7885e3c1

**Comment by skomra** [comment]
included in input-wacom-0.40.0
