### ISSUE TITLE
Ubuntu 20.04 crashes when ThinkPad Pen Pro touches screen of Thinkpad L13 Yoga Gen 2

### ISSUE THREAD

**Issue by therunomask** [linuxwacom/input-wacom#253]
While I am still able to click buttons on the screen using my fingers, the system crashes consistently every time the pen touches the screen. In this case, the screen freezes and the system does not react to anything I do, also ctr+alt+F3 does not change anything.

I used the pen until a few weeks ago, it was working fine then. When I tried again yesterday the bug appeared for the first time.

Any help would be appreciated.

**Comment by lsitongia** [comment]
I just want to leave a "me, too". On this.

**Comment by lsitongia** [comment]
I just want to leave a "me, too". I don't see anything logged in the system or X11. It's really odd. I touch the screen with the active stylus and the system just locks up. Display doesn't change, still shows whatever was there. Keyboard is inactive. Mouse inactive. Internal or external, doesn't matter. Have to power-cycle the laptop.

**Comment by punyidea** [comment]
I experienced this issue too, and reverted to kernel version 5.8.0-44-generic which did not have this issue.
My issue is in part related to #246 as I've already installed the new driver version 0.47.0.

**Comment by punyidea** [comment]
See issue #234 as well?

**Comment by lsitongia** [comment]
> See issue #234 as well?

In my case it is a Wacom digitizer in the screen. The laptop locks up. It is not possible to perform any commands. Must hard reboot.

**Comment by therunomask** [comment]
> I experienced this issue too, and reverted to kernel version 5.8.0-44-generic which did not have this issue.
> My issue is in part related to #246 as I've already installed the new driver version 0.47.0.

While this does not fully resolve the issue, it's a good workaround for the time being. Thanks

**Comment by punyidea** [comment]
#246 has a potential workaround if the drivers have been installed from source. (see secure boot link as well).

Possible that updating to kernel 5.8.0-49-generic fixes your issue as well.

**Comment by lsitongia** [comment]
I just got 5.8.0-49-generic as a regular update in the Ubuntu Software app, and that has fixed the problem.

**Comment by therunomask** [comment]
> I just got 5.8.0-49-generic as a regular update in the Ubuntu Software app, and that has fixed the problem.

It worked for me too.
