### ISSUE TITLE
Detection region becomes half sized when unplugging, plugging tablet.

### ISSUE THREAD

**Issue by Davidy22** [linuxwacom/input-wacom#266]
When I unplug and plug the tablet back in, the usable tablet region becomes only the left half of it. Can provide more logs/docs on request.

Intuous CTL-4100, Mint 20.2, 5.4.0-80-generic

**Comment by Joshua-Dickens** [comment]
Hi Davidy22, this seems to be a previously solved issue #174 
Please try the stated fix for that issue and see if it works.

**Comment by Davidy22** [comment]
I have noticed other issues where a workaround is prescribed, and the workaround does work, but the issues are all closed for some reason. I'd usually close my own issue for being a duplicate but the other issues are all closed while the bug is still present and there's only a workaround.

**Comment by Joshua-Dickens** [comment]
Alright so I'm trying to find a more permanent solution for you, however I'm trying to replicate your issue but I'm struggling to reproduce the issue. Could you go more into detail on the steps you take to cause the issue, and also run this [sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) with the tablet connected and post the resulting tar here? Thanks

**Comment by Davidy22** [comment]
To note, the affected devices aren't the full range of wacom products, although they do seem to be [well known](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#special-cases). Issue occurs when plugging in device, but works if device was plugged in at startup. Below are both the device in normal mode and device in the wrong (android) mode

[wacom_android.tar.gz](https://github.com/linuxwacom/input-wacom/files/7043207/wacom_android.tar.gz)
[wacom_desktop.tar.gz](https://github.com/linuxwacom/input-wacom/files/7043209/wacom_desktop.tar.gz)

**Comment by Joshua-Dickens** [comment]
I replicated the issue at hand. The cause of the problem seems to be fwupd, disabling the service then rebooting should provide the solution you need.
I used the following commands to disable the service.
`
sudo systemctl stop fwupd.service
sudo systemctl disable fwupd.service
sudo systemctl mask fwupd.service
`

Please try the proposed solution and let me know if it works.

**Comment by Davidy22** [comment]
Hum, this alternate workaround seems to work even without rebooting actually, can unplug/plug the tablet and it starts in the correct mode. Need line breaks before each sudo, but I assume github just mangled your formatting. Still a workaround, but potentially implies that the fix should be implemented there. Will check further, may close this if a fix happens/happened there.

**Comment by Pinglinux** [comment]
@Davidy22 Thank you for your prompt replies. Since it is an issue related to fwupd, can we close this request?

**Comment by Davidy22** [comment]
The earlier test does seem to indicate it's probably fwupd. I headed over there and the maintainer says it's fixed in the latest release, although getting it installed is fairly involved and I haven't been able to check if it is fixed. [This resource](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#special-cases) could possibly be updated, and repos are going to need to have fwupd updated to 1.6.3 or later to fix this.

**Comment by Davidy22** [comment]
Alright, fwupd 1.6.4 released with a snap that I could install and I can probably confirm that it does indeed fix the issue, which means that the resource in the documentation will be obsolete and removable once all distros update fwupd.
