### ISSUE TITLE
trying to compile input_wacom on centos 7.7 stock getting struct errors

### ISSUE THREAD

**Issue by gmcgill-d2** [linuxwacom/input-wacom#277]
kernel is 3.10.0-1062.9.1.e17.x86_64

Error compiling input_wacom 

complains about struct type value where scalar is required
![image](https://user-images.githubusercontent.com/92749766/137781163-4d2693de-35fe-4f53-a412-750d905fa77d.png)

**Comment by jigpu** [comment]
I have been unable to reproduce this issue with either the original release of 7.7 (kernel 3.10.0-1062) or a fully updated version (kernel 3.10.0-1062.18.1). Please try updating your distro and re-open this issue if the problem persists.
