### ISSUE TITLE
Scrolling Ring Wheel 

### ISSUE THREAD

**Issue by penny-bit** [linuxwacom/input-wacom#279]
Hi,
I own a **Wacom Intuos Pro M** everything works fine for me except ring wheel.
In **ubuntu 21.10** wacom settings I would like to map the **ring wheel** to the **mouse scroll wheel** (not a keystroke) but I couldn't do it.
I've looked around, google, forums, etc. but nobody seems to have this issue. This is the `xsetwacom` output if it might help:

```
xsetwacom -s get "Wacom Intuos Pro M Pad pad" all
Property 'Wacom Tablet Area' does not exist on device.
xsetwacom set "Wacom Intuos Pro M Pad pad" "Button" "1" "button +1 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "Button" "2" "button +2 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "Button" "3" "button +3 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "Button" "8" "button +8 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "Button" "9" "button +9 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "Button" "10" "button +10 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "Button" "11" "button +11 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "Button" "12" "button +12 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "Button" "13" "button +13 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "ToolDebugLevel" "0"
xsetwacom set "Wacom Intuos Pro M Pad pad" "TabletDebugLevel" "0"
xsetwacom set "Wacom Intuos Pro M Pad pad" "Suppress" "2"
xsetwacom set "Wacom Intuos Pro M Pad pad" "RawSample" "4"
Property 'Wacom Pressurecurve' does not exist on device.
xsetwacom set "Wacom Intuos Pro M Pad pad" "Mode" "Absolute"
Property 'Wacom Hover Click' does not exist on device.
xsetwacom set "Wacom Intuos Pro M Pad pad" "Touch" "off"
Property 'Wacom Hardware Touch Switch' does not exist on device.
xsetwacom set "Wacom Intuos Pro M Pad pad" "Gesture" "off"
xsetwacom set "Wacom Intuos Pro M Pad pad" "ZoomDistance" "0"
xsetwacom set "Wacom Intuos Pro M Pad pad" "ScrollDistance" "0"
xsetwacom set "Wacom Intuos Pro M Pad pad" "TapTime" "250"
Property 'Wacom Proximity Threshold' does not exist on device.
Property 'Wacom Rotation' does not exist on device.
xsetwacom set "Wacom Intuos Pro M Pad pad" "RelWheelUp" "1" "button +5 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "RelWheelDown" "2" "button +4 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "AbsWheelUp" "3" "button +4 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "AbsWheelDown" "4" "button +5 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "AbsWheel2Up" "5" "button +4 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "AbsWheel2Down" "6" "button +5 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "StripLeftUp" "1" "button +4 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "StripLeftDown" "2" "button +5 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "StripRightUp" "3" "button +4 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "StripRightDown" "4" "button +5 "
xsetwacom set "Wacom Intuos Pro M Pad pad" "Threshold" "0"
xsetwacom set "Wacom Intuos Pro M Pad pad" "BindToSerial" "0"
Property 'Wacom Pressure Recalibration' does not exist on device.
xsetwacom set "Wacom Intuos Pro M Pad pad" "PanScrollThreshold" "13"
```

Does anybody know how to do it? Is there a way to do it?

I hope someone can help me with that.

Thank you

**Comment by Pinglinux** [comment]
Did you check "Wacom Tablet" under Settings?

**Comment by penny-bit** [comment]
Yes I did, but I can only put keystroke not proper event. The scroll wheel of the mouse it's an event not a keystroke.
This is an old issue never resolved to me. On KDE for example in wacom settings you can assign the mouse scroll to the ring wheel of the pad, on gnome you cannot.
Here a issue on gnome [gitlab](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/118).
As on KDE this option is available I don't think it's so hard to implement it on gnome. 
On macOS and Win this option is there by default, it's normal behavior of the tablet.

Thank you

**Comment by Pinglinux** [comment]
I see. That's a bug (or feature request :) for Gnome to take care of. It used to work as a scroll wheel by default in xf86-input-wacom. Now the button and wheel features are defined in Gnome-Control-Center, if you are using Gnome Desktop Environment. Another issue I'd like Gnome to fix is to allow users to assign more than one letter/key to the buttons.

**Comment by jigpu** [comment]
For the benefit of others, this issue has been reported to GNOME for quite some time (I'm sure @penny-bit is already aware of these two active issues, having filed/commented in them). I wish this was something that we could trivially fix, but GNOME's codebase is very complex and their developers are in a better position than we are to make a change...
* https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1007
* https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/118
