### ISSUE TITLE
Pen followed despite being lifted from surface

### ISSUE THREAD

**Issue by thekswenson** [linuxwacom/input-wacom#281]
I have a new Dell Latitude 7320 Detachable with and active pen (PN7320A).  Upon installing Ubuntu 21.10 I was happy to find that the pen works to a certain extent. It will work as expected for a certain amount of time but will, after not very long, enter into a state where the lifted pen will still be registered as the lightest possible touch of the pen. This results in all of the strokes being joined together like so:

![Screenshot from 2021-10-25 12-16-55](https://user-images.githubusercontent.com/9959942/138686234-c48699e2-764b-4d97-bca5-8c10e9f4d73f.png)

The only way to stop a stroke is to move the pen far from the surface.
When in this state, I ran `libinput debug-gui` and things seem the same as when in the normal state (where lifting the pen stops the stroke). Here is a video from the libinput debug-gui:

https://user-images.githubusercontent.com/9959942/138687028-1a7611d3-b38f-4f78-ac08-16d6a474fe5b.mp4

**Comment by Pinglinux** [comment]
Please share the output of **libinput record** for the following two cases in separate files:
 1. run **libinput record** when the issue occurs. Move on the surface then lift it up and move around a bit
 2. run **libinput record** when there is no issue. Move on the surface then lift it up and move around a bit

**Comment by thekswenson** [comment]
I know how to trigger the bug now. All works well until I write with the lightest of touches, at which point the bug is triggered. Here are the yaml files output by `libinput record`.

[with_issue.txt](https://github.com/linuxwacom/input-wacom/files/7416700/with_issue.txt)
[no_issue.txt](https://github.com/linuxwacom/input-wacom/files/7416698/no_issue.txt)

**Comment by thekswenson** [comment]
Here are two simpler use cases where I draw a single stroke and then move while hovering the pen for a bit.

[no_issue_simple.txt](https://github.com/linuxwacom/input-wacom/files/7417817/no_issue_simple.txt)
[with_issue_simple.txt](https://github.com/linuxwacom/input-wacom/files/7417818/with_issue_simple.txt)
.

**Comment by Pinglinux** [comment]
@thekswenson Thank you for the records. I see the pressure stayed at 117, 118, 134, 239, and 240 when issue happened. That normally happens to the stylus that used for a while. It registers a non-zero pressure even before touches the tablet surface, which means the tip doesn't return back to its released state when it is not in use.

Are you using xf86-input-wacom or libinput driver? With xf86-input-wacom, you could use xsetwacom to reset the tool's Threshold to a number, say 250, so the tool's pressure returns to zero when it is at 250 or below. Hi @whot, do you have "tricks" for @thekswenson to play if his system runs with libinput?

**Comment by whot** [comment]
no tricks needed, pressure offset for worn-out tools is built-into libinput, see [the documentation](https://wayland.freedesktop.org/libinput/doc/latest/tablet-support.html#pressure-offset-on-worn-out-tools) and defaults to up to 20% of the pressure range, so 250 here shouldn't be a problem.

You should see a message "Pressure offset detected on tool..." in the logs if you're using libinput

**Comment by thekswenson** [comment]
Thanks folks. This is a new machine out of the box, so I'm a little surprised. I guess it's a manufacturing defect. :/

Thanks for all the help! I'll look into the references you gave me.

**Comment by thekswenson** [comment]
I remove the pen tip and then reinstalled it.  I haven't had the problem crop up again.
I should have guessed there was a hardware bug!   Thanks folks!
