### ISSUE TITLE
wacom tablet interfering with hard disk power.

### ISSUE THREAD

**Issue by bebinalpha** [linuxwacom/input-wacom#295]
On connecting Wacom CTL-6100WL Intuos Medium Bluetooth Pen Tablet to my pc using USB Cable or bluetooth and then leaving it to idle for some time, after some time the hard disk in my pc constantly making a spinning up and then spin down sound. The kind of sound it makes while pc enters sleep mode and then wake up. The sound stops after disconnecting the tablet from the pc. I am using Manjaro and  kernel 5.15.7-1. may be the battery from the tablet is interfering with the power save mode i don't know..  please advise.

**Comment by bebinalpha** [comment]
uninstalling TLP have fixed the problem

**Comment by Pinglinux** [comment]
Thank you for sharing your result with us @bebinalpha
