### ISSUE TITLE
Using the stylus on the tablet, doesn't take over the position of the mouse cursor

### ISSUE THREAD

**Issue by K4LCIFER** [linuxwacom/input-wacom#301]
I am not sure if this is intended behaviour or not, but when you use the stylus, it doesn't take over the original position of the mouse. In fact, it operates as if there are two independant mouse cursors: one cursor for the actual system mouse, and the other cursor for the stylus.

**Comment by jigpu** [comment]
This is normal behavior for the GNOME desktop when using its Wayland backend. They have decided to have the stylus and mouse operate independent pointers. Other desktops (e.g. GNOME in X11, KDE, etc.) use a more traditional single pointer for both stylus and mouse.
