### ISSUE TITLE
Lenovo Yoga 7 14ACN6 Touch/Stylus Sometimes Stops Working

### ISSUE THREAD

**Issue by throwm8** [linuxwacom/input-wacom#304]
Hello,

I'm having some problems getting the touchscreen on my 14acn6 to work reliably under Linux 5.16.2. As the title says the screen randomly stops recognizing my finger or stylus and stays that way. Unloading and loading the wacom kernel module fixes this temporarily but doesn't prevent it from occurring again. I was monitoring both the finger and stylus info with evemu-record during the last time the screen stopped responding to my finger and the log ended with this
```
E: 1.393140 0000 0000 0000      # ------------ SYN_REPORT (0) ---------- +10ms
E: 1.402903 0003 0036 3015      # EV_ABS / ABS_MT_POSITION_Y    3015
E: 1.402903 0003 0001 3015      # EV_ABS / ABS_Y                3015
E: 1.402903 0000 0000 0000      # ------------ SYN_REPORT (0) ---------- +9ms
E: 1.432966 0003 0035 6268      # EV_ABS / ABS_MT_POSITION_X    6268
E: 1.432966 0003 0000 6268      # EV_ABS / ABS_X                6268
E: 1.432966 0000 0000 0000      # ------------ SYN_REPORT (0) ---------- +30ms
E: 1.551572 0003 0039 -001      # EV_ABS / ABS_MT_TRACKING_ID   -1
E: 1.551572 0001 014a 0000      # EV_KEY / BTN_TOUCH            0
E: 1.551572 0000 0000 0000      # ------------ SYN_REPORT (0) ---------- +119ms
```

I don't know if this is significant but at first I thought it had something to do with the negative tracking ID but the same message was printed in the earlier parts of the log(when the screen was still working properly). 

There's absolutely nothing in dmesg or Xorg.log indicating any errors. The laptop seems to have a WACF2200 connected via i2c.
```[    2.359155] input: WACF2200:00 056A:52B0 Touchscreen as /devices/platform/AMDI0010:02/i2c-2/i2c-WACF2200:00/0018:056A:52B0.0002/input/input9
[    2.360935] input: WACF2200:00 056A:52B0 as /devices/platform/AMDI0010:02/i2c-2/i2c-WACF2200:00/0018:056A:52B0.0002/input/input10
[    2.361044] input: WACF2200:00 056A:52B0 as /devices/platform/AMDI0010:02/i2c-2/i2c-WACF2200:00/0018:056A:52B0.0002/input/input11
[    2.361124] input: WACF2200:00 056A:52B0 as /devices/platform/AMDI0010:02/i2c-2/i2c-WACF2200:00/0018:056A:52B0.0002/input/input12
[    2.361193] input: WACF2200:00 056A:52B0 Mouse as /devices/platform/AMDI0010:02/i2c-2/i2c-WACF2200:00/0018:056A:52B0.0002/input/input13
[    2.361268] hid-generic 0018:056A:52B0.0002: input,hidraw1: I2C HID v1.00 Mouse [WACF2200:00 056A:52B0] on i2c-WACF2200:00
[2.632101] wacom 0018:056A:52B0.0002: hidraw1: I2C HID v1.00 Mouse [WACF2200:00 056A:52B0] on i2c-WACF2200:00
```
The output of the sysinfo script can be found here [https://github.com/linuxwacom/wacom-hid-descriptors/issues/195](url)

Thanks.

**Comment by jigpu** [comment]
This is most likely the same issue as #288. The 5.16.2 kernel that you are using is affected by a bug which causes touch to stop working after a short time. A fix has been submitted upstream and should be available soon.

As a temporary workaround, you can try building/installing a development version of input-wacom as described at https://github.com/linuxwacom/input-wacom/issues/288#issuecomment-1011465509

**Comment by throwm8** [comment]
That's great to hear, I compiled input-wacom myself later after creating the issue and the problem never happened again. Thanks for the fix.
