### ISSUE TITLE
Lenovo X1 Titanium pens (2) stop working after a few minutes

### ISSUE THREAD

**Issue by rfmaclellan** [linuxwacom/input-wacom#309]
I have tried both the Lenovo Precision Pen that comes with the laptop and a Bamboo Ink Plus and both work after booting up for a minute, then they stop working, then they start. This happens for about 5 min then they stop working and don't start working again. Touch continues to work. The pens, and now the tablet since I submitted the info for a new tablet definition last week, are recognized by Ubuntu 20.04. Everything works fine in Windows 10 and now 11. I installed the latest version of wacom I pulled from git (it now has my tablet definition so I know it's using the latest).

**Comment by Pinglinux** [comment]
Do you see any pen related messages from "dmesg" or ~/.local/share/xorg/Xorg.0.log when the issue happened? You can also run one of the tools here (https://github.com/linuxwacom/input-wacom/wiki/Analysing-kernel-events) to see if the input events were reported properly

**Comment by Pinglinux** [comment]
Closing the issue due to lack of details.
