### ISSUE TITLE
how to update packages?

### ISSUE THREAD

**Issue by dln949** [linuxwacom/input-wacom#31]
(I am not sure this is the correct place to post this question.)  

I am running Ubuntu 17.10.  

I have the Wacom Intuos tablet.  At first it did not work.  Then, following the instructions at [https://linuxwacom.github.io/](url) , I installed the three packages.  Now the tablet works great!  

Here are my questions:  

If there are updates to any of these packages, how will I know about them?  And, what is the process to update them?  Will the updates for these packages be part of the the update process that the Ubuntu OS on my computer always notifies me about?

**Comment by jigpu** [comment]
Hi there,

If you compiled and installed everything from source (which is what it sounds like), there is no automatic update mechanism. That said, the files will (usually) overwrite those shipped by the OS, and any update provided by your distribution will similarly overwrite the version you've installed from source. There is a small chance that a distribution update could wipe out your compiled version, but most distributions do not send out anything but the very latest driver as updates anyway.

The one exception to this is the "input-wacom" driver, which is tied to specific kernel versions. If your distro sends out a kernel update, you will probably need to recompile and reinstall the "input-wacom" driver to get your tablet working again.

Generally speaking you shouldn't need to continously update to the latest driver version as we make releases. Regardless, we do announce every release on our "linuxwacom-announce" mailinglist that you can subscribe to at https://sourceforge.net/projects/linuxwacom/lists/linuxwacom-announce. You could also instead look for services that will provide a notification when a new release is posted to our Github projects.
