### ISSUE TITLE
Ryzen 5000 series

### ISSUE THREAD

**Issue by Cecr0pass** [linuxwacom/input-wacom#314]
I am writing this because those who face the same problem may find it useful. I had a Wacom One Pen tablet on an old DELL laptop with linux mint and everything were fine. I decided to use again linux mint on this new laptop for speed reasons. A Lenovo thinkpad 3 with Ryzen 5000.
The tablet does not works. It is there on control panel, but no signal. I tried to reinstall the driver. Nothing. ''wacom module is not active''.
After many hours of search I found that it is about Ryzen and AMD Radeon graphics, not about the driver or the tablet. 
The solution was the installation of 5.14-oem kernel 
Now it works.
Thanks and have a nice day.

**Comment by Pinglinux** [comment]
@Cecr0pass  Thank you for sharing your experience here. I'm closing the issue since it's not an input-wacom issue.
