### ISSUE TITLE
are these directories needed?  

### ISSUE THREAD

**Issue by dln949** [linuxwacom/input-wacom#32]
(I am not sure this is the correct place to post this question.)

I am running Ubuntu 17.10.

I have the Wacom Intuos tablet. At first it did not work. Then, following the instructions at https://linuxwacom.github.io/ , I installed the three packages. Now the tablet works great!

Here is my question:

By following those instructions, I see that two directories were created in my "home" directory:  

input-wacom-0.40.0 , and, libwacom

Do I need to keep those directories and their contents in order for the wacom packages to work?

**Comment by Pinglinux** [comment]
No, you do not need to keep those directories if you followed the installation steps. The driver/files should be installed to the proper directories on your systems already.
