### ISSUE TITLE
Wayland, Xorg and xsetwacom

### ISSUE THREAD

**Issue by enkidu-smith** [linuxwacom/input-wacom#327]
Ubuntu have made Wayland the default, this means that xsetwacom can no longer be used in the default configuration to configure Wacom tablets. I've read around and I sort of understand the reasons for this. I've switched to using Xorg and I'm quite happy with that, but there will be new Linux users with new Wacom tablets who don't understand the issue and will not be able to configure their tablets, and will therefore be disappointed in them.

I'm talking here about things like the tablet's Area parameter which I modify, but which is not visible or modifiable except by xsetwacom under Xorg. Am I correct in saying that there is currently no tool to modify these sorts of parameters under Wayland/XWayland?

If there isn't such a tool, is there any way that such a tool could be written? Is there an API that could be accessed to write it?

**Comment by Pinglinux** [comment]
Hi @enkidu-smith, Thank you for sharing your ideas. As you've pointed out, xsetwacom relies on the Xorg/X server. The xsetwacom is an utility that lives in userland/desktop environment. For future users, they will need to use the utilities provided by the desktop environment they choose. For most users, Gnome will be their default environment. In theory, Gnome Control Center/Wacom Tablet Panel supports most of the features that xsetwacom provided. But, there are missing pieces here and there. If you have time, please test Gnome Setting's "Wacom Tablets" panel and report issues directly to [GNOME issues](https://gitlab.gnome.org/groups/GNOME/-/issues). You can also request for new features there.

The linuxwacom project works on the driver and low level libraries. We can help users to setup their system/driver. But, userland features are not implemented here. With that said, I'm going to close your request to input-wacom, which is a project solely for kernel driver.
