### ISSUE TITLE
how to make wacom working automatically at startup?

### ISSUE THREAD

**Issue by pangyulei** [linuxwacom/input-wacom#332]
my wacom not working at startup, no response when I moving pens on tablet, can not move cursor
but Debian can detect it, it shows in Setting -> Input Devices -> Graphic Tablet
and after I plug out then re-plug in usb, it works perfect
but after reboot, I have to do that again make it work...
 so is there anyway to make it work automatically at startup?

**Comment by Pinglinux** [comment]
Which version of Debian do you have the issue with? Did you update/change the system yourself? What kernel version do you use?

**Comment by pangyulei** [comment]
> Which version of Debian do you have the issue with? Did you update/change the system yourself? What kernel version do you use?

already solved, it seems to be debian's compatible bugs with qt, because if I use kde or lxqt, after update nvidia driver and reboot, wacom not working, but if I use gnome or xfce, it works fine after update nvidia driver
