### ISSUE TITLE
Wacom Cintiq 24HD Pen stopped working

### ISSUE THREAD

**Issue by mnlipp** [linuxwacom/input-wacom#34]
My Wacom Cintiq 24HD Pen stopped working when I upgraded the kernel to 4.16.x. Booting fc26 (X Server 1.19.6) with kernel 4.15.17 (from fc25) makes it work again.

"Working" in this case means that the cursor does no longer follow the pen movements. Actually, nothing that I do with the pen has any effect. The X server log files don't show any problems. The device is detected and registered.

Any hints?

**Comment by jigpu** [comment]
I've just tried using a Cintiq 24HD with a fully-updated Fedora 27 install (4.16.15-200 kernel) and don't see any problems. I've occasionally had issues in the past with the Cintiq randomly stopping until I turn it off and then on again; perhaps you're experiencing something similar?

**Comment by mnlipp** [comment]
After using the old kernel for a long time, I finally upgraded to Fedora 28 today. The situation is the same as initially described. `xinput` shows the wacom "pen" device, `xsetwacom` lists it, but it doesn't work.

It *does* start working after unpluging and re-plugging the USB connection to the tablet. As the plug isn't easily reachable in my case ("built-in" device), I've come up with this reset script:

```
#!/bin/bash

for d in /sys/bus/usb/devices/*; do 
  if [ -r "$d/idVendor" ]; then
    idVendor=`cat $d/idVendor` 
    idProduct=`cat $d/idProduct` 
    if [ "$idVendor" = "056a" -a "$idProduct" = "00fa" ]; then
      echo 0 > "$d/authorized"
      echo 1 > "$d/authorized"
    fi
  fi
done
```
Executing this on boot fixes things, but this is, of course, only a hack, not a solution.

**Comment by jigpu** [comment]
What kernel were you using previously that worked for you? That might provide a hint of where to start looking. Also, does the tablet always require the reset after boot-up? Do you ever have to reset after the machine is up and running? Does turning the Cintiq off and then on also fix the issue, or does only unplugging (or resetting) the USB work?

**Comment by mnlipp** [comment]
Kernel 4.15.17 was the last that worked (see above). Yes, it always requires the reset. 
> Do you ever have to reset after the machine is up and running?

I've only run the upgraded machine for a short time today (about 2 hours) during which it was stable. I'll have to supply this information later. 
> Does turning the Cintiq off and then on also fix the issue, or does only unplugging (or resetting) the USB work?

Turning off (unplugging the power) fixes the problem. In fact, this is what I found out first. It was this  observation that made me try to unplug the USB connection as a more gentle approach (and eventually the software reset as the mildest "solution"). I'll have to check if switching to standby and reactivating helps, I didn't try that.

**Comment by mnlipp** [comment]
> Does turning the Cintiq off and then on also fix the issue, or does only unplugging (or resetting) the USB work?

Finally remembered to check, yes, it does.

**Comment by jigpu** [comment]
Thanks. My own 24HD just experienced its "stops working" issue and I was able to revive it with your script. I'd suspected that my device was just flaky, but it looks like this is probably the same issue you're seeing. I don't see anything suspicious in my logs, but I'll keep a closer eye on the issue. Next time it happens I'm going to try dumping the USB traffic to see if it's talking but our driver isn't listening...

**Comment by jigpu** [comment]
Looks like there's no USB traffic being sent by the 24HD at all after the issue is triggered. Still not sure of the actual trigger of if its a driver or firmware bug...

**Comment by mnlipp** [comment]
As the behavior is related to booting a newer kernel, it should be the driver in that newer kernel, shouldn't it? Or does the driver include some vendor blob that has been updated somewhere between kernel 4.15.17 and 4.16.x?

**Comment by jigpu** [comment]
That would make sense, though I'm somewhat skeptical that a kernel change is the actual cause of the problem (as opposed to merely triggering an existing problem). My 24HD has been acting up for a long time. I can roll back my own kernel to double-check, but I suspect it was having issues even before 4.15 was released. Also, none of the four changes to our driver in that period (kernel commits torvalds/linux@99acedadde, torvalds/linux@8341720642, torvalds/linux@791ae27373, torvalds/linux@403c0f681c, and torvalds/linux@c947218951) would plausibly impact the 24HD. A change somewhere else in the kernel (e.g. the underlying USB subsystem) could be responsible, but isolating the offending commit is going to require quite a bit of compiling and testing ("git bisect" estimates 13 compile/test rounds).

**Comment by mnlipp** [comment]
In my case, the issue is definitely related with the kernel change. I boot Linux from a USB-Stick in four different rooms which are all equipped with 24HDs. In all of them everything worked reliably up to 4.15.17 since at least 2016. And in all of them I now have to turn off/on the 24HD after startup to make the pen work again. 

(Of course, this observation does in no way exclude the possiblity that the root cause is in the underlying USB system.)

**Comment by Pshemas** [comment]
also suffer from this issue. On my end it is definitely triggered by kernel change. When I boot OpenSUSE LEAP 15 with stock kernel (4.12) all works as expected. As soon as I boot with 4.20 immediately I get this problem (and as with others unplugging and plugging the device again makes the device start working).
On my end it happens with Cintiq 22.

**Comment by Pinglinux** [comment]
Looks like something changed after kernel 4.15 which affected the tablet. Can one of you bisects the code to figure out which patch is the root cause?

Thank you for reporting the issue!

**Comment by Pinglinux** [comment]
Do they work with newer distributions now?

**Comment by mnlipp** [comment]
I currently don't have access to the rooms with the Cintiq. Will be a while until I can provide the information.

**Comment by Pinglinux** [comment]
The root cause of those Cintiq related issues are not in Wacom driver, especially since the issue disappear after a power/USB cycle. It should be in the kernel/system configuration for kernels later than 4.15.17+. Feel free to open a new request if systems running kernel 5.18+ still have the issue.
