### ISSUE TITLE
Build Failed .configure:line

### ISSUE THREAD

**Issue by orlandoinsane** [linuxwacom/input-wacom#340]
Hi! I'm new to all of this, so hope I don't come up as being too much of a newb.

When running the build script I get an immediate issue and fail:

./configure: line 1534: config.log: Permission denied
./configure: line 1544: config.log: Permission denied
Build Failed

any help would be lovely, am installing on Ubuntu Budgie, using an old x61t ibm laptop.

Thanks,

Dan

**Comment by Pinglinux** [comment]
Your question is most likely an "Ubuntu Budgie" question. What tablet are you using?

**Comment by Pinglinux** [comment]
Not a driver or build script issue.
