### ISSUE TITLE
Build fails on ubuntu 22.04 kernel 5.10 aarch64

### ISSUE THREAD

**Issue by Pedrocasf** [linuxwacom/input-wacom#343]
Building the main branch with 
if test -x ./autogen.sh; then ./autogen.sh; else ./configure; fi && make && sudo make install || echo "Build Failed" 
fails with several
input-wacom/4.5/wacom_wac.c:4168:23: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
error, forbidden warning:wacom_wac.c:4168
 4168 |         for (i = 0; i < wacom->led.count; i++)

**Comment by Pinglinux** [comment]
Can you paste the whole build output with errors here?

Also, I'm curious about the reason you want to build input-wacom on Ubuntu 22.04. Do you try to make a tablet work? If yes, which tablet?

**Comment by Pinglinux** [comment]
I see the "warning" treated as error issue. That block of code isn't new. It is in the older kernels and upstream kernel. We've been compiling the driver without issues. I'd think something is different in your development environment setup.
