### ISSUE TITLE
Problem with no drivers showing up after installing input-wacom

### ISSUE THREAD

**Issue by ewhite42** [linuxwacom/input-wacom#345]
Hi all, hopefully it's ok to ask this here. I just followed the steps listed on this page: https://github.com/linuxwacom/input-wacom/wiki/Installing-input-wacom-from-source to attempt to install input-wacom on my Ubuntu 22.04 laptop in order to use my Wacom Cintiq (13HD), and although I can get through the installation steps without any failures, after I reboot my computer (as instructed) and run: `grep "" /sys/module/wacom*/version` with the tablet plugged in, I get the following output: `grep: /sys/module/wacom*/version: No such file or directory`. Trying to run `sudo rmmod wacom` yields the error: `rmmod: ERROR: Module wacom is not currently loaded` (similar results occur when I try `sudo rmmod wacom_w8001`, and the modprobe commands just return no output). 

Just curious what is going on here? Any advice would be much appreciated, thanks for considering this (and my apologies if I've posted this to the wrong place).

**Comment by Pinglinux** [comment]
If you are running Ubuntu 22.04 with a Cintiq 13HD, you do not need to install/update anything for the tablet to work. If it wasn't working, please provide the output of "dmesg" here.

**Comment by Pinglinux** [comment]
Close this issue until we get further information.
