### ISSUE TITLE
initialization problem with Cintiq 22HD?

### ISSUE THREAD

**Issue by Nuliel** [linuxwacom/input-wacom#351]
Hello,
I try to help someone with a Wacom Cintiq 22HD, he is on Ubuntu 22.04.
The tablet is not usable if he boots on Ubuntu with tablet plugged before booting, but if he unplugs and plugs the tablet after Ubuntu boot, tablet becomes usable. 
Reloading wacom module with modprobe doesn't help.
Note that reloading wacom module when tablet is usable makes it unusable. 
Is there an initialization problem for this model?
Thanks

**Comment by Pinglinux** [comment]
What do you see in the dmesg output, when the tablet is connected before you disconnect and reconnect the tablet?

**Comment by Nuliel** [comment]
Note that when tablet is powered off and powered on using power button of the tablet, the result is the same than when usb cable is disconnected/reconnected. Here is the dmesg output asked:
[dmesg.txt](https://github.com/linuxwacom/input-wacom/files/11193830/dmesg.txt)

**Comment by Pinglinux** [comment]
demsg looks fine. If power cycle or reconnect the device worked, it could be something in the userland. Which Windows system, Xorg or Wayland, are you using?

**Comment by Nuliel** [comment]
I use Xorg, because with wayland xsetwacom list says "Wayland devices found but this tool is incompatible with Wayland"

**Comment by Pinglinux** [comment]
Then, please post your Xorg.0.log here, after you disconnected or power cycled the tablet. Basically, after you know the tablet is working...
