### ISSUE TITLE
No timeout for pen battery removal

### ISSUE THREAD

**Issue by stuarthayhurst** [linuxwacom/input-wacom#353]
As expected, bringing my Lenovo Active Pen 2 close to the screen reports a battery. When removing it, the battery doesn't disappear until the driver is reloaded. Even if the pen doesn't report it has left, I would've thought there would be a timer to remove the battery after a while.

Please let me know if my explanation wasn't very clear, or if you need any information from my device (Wacom 52D5)

Thanks :)

**Comment by Pinglinux** [comment]
We'll consider your battery timeout suggestion in the kernel driver. It is in our to-do list.

**Comment by stuarthayhurst** [comment]
Thank you :)

**Comment by jigpu** [comment]
Patch submitted to the LKML for consideration: https://lore.kernel.org/linux-input/20231114235729.6867-1-tatsunosuke.wacom@gmail.com/

**Comment by stuarthayhurst** [comment]
> Patch submitted to the LKML for consideration: https://lore.kernel.org/linux-input/20231114235729.6867-1-tatsunosuke.wacom@gmail.com/

Patch working great on my system, thanks!

**Comment by stuarthayhurst** [comment]
#406 solves this, thanks
