### ISSUE TITLE
Ubuntu 22.04 Bamboo Ink Plus behaves like a mouse not a pen

### ISSUE THREAD

**Issue by keithjnewman** [linuxwacom/input-wacom#360]
My wacom bamboo ink plus won't stay connected to Bluetooth on Ubuntu 22.04. If I put the Wacom into pairing mode it is identified and I can connect it, but it then immediately disconnects.

My laptop is a Dell Inspiron 7306 2in1, it is dual boot between Windows 11 and Ubuntu 22.04. The same hardware works fine on Windows 11, with the Wacom connected by Bluetooth.I therefore believe this issue to be software rather than hardware related.

Currently the stylus acts like a mouse, it is not pressure sensitive, and to write with it, I have to hold down the equivalent of the left mouse button.

I have compiled the latest input-wacom from source using the instructions I found at https://github.com/linuxwacom/input-wacom/wiki/Installing-input-wacom-from-source, but this has not helped.

Any pointer on how I can get this stylus working properly under Ubuntu, would be gratefully received.

**Comment by Pinglinux** [comment]
That device is not supported on Linux-based systems.

With that said, you may find something useful at https://github.com/tuhiproject/tuhi. Good luck!
