### ISSUE TITLE
input-wacom line 38/2275 possible syntax related error help

### ISSUE THREAD

**Issue by abyssmal131** [linuxwacom/input-wacom#373]
Hello,

So, I havea Cintiq 16 on Nobara Linux (a fedora fork) that doesn't work when I plug it in. The computer sees it, none of my inputs go through/in settings I can neigher calibrate or use the "Test Your Settings" function or move my pointer at all. So I'm trying to go through these Linux Wacom Project.

I got the xf86-input-wacom section going, I can see the cintiq 26 has a .tablet file in /share/libwacom, the only thing I can't do is install the kernel driver as explained. I've downloaded the file, and run the provided command and this is what I get:

----------------------------------------------------------------------------------------------------------
BUILD ENVIRONMENT:
       linux kernel - yes 4.5
      kernel source - yes /lib/modules/6.3.7-200.fsync.fc37.x86_64/source

NOTE: The kernel drivers included in this package are only tested with the
X Wacom driver built from xf86-input-wacom. If you are running an X server
version older than 1.7, please use the drivers provided by the linuxwacom
package.

Please run 'make && make install'.
make  all-recursive
make[1]: Entering directory '/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0'
Making all in 4.5
make[2]: Entering directory '/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5'
    Building input-wacom drivers for 4.5 kernel.
make -C /lib/modules/6.3.7-200.fsync.fc37.x86_64/source M=/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5
make[3]: Entering directory '/usr/src/kernels/6.3.7-200.fsync.fc37.x86_64'
  CC [M]  /home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.o
/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c: In function ‘wacom_update_name’:
/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c:38:41: error: implicit declaration of function ‘hid_is_using_ll_driver’; did you mean ‘wacom_is_using_usb_driver’? [-Werror=implicit-function-declaration]
   38 | #define wacom_is_using_usb_driver(hdev) hid_is_using_ll_driver(hdev, &usb_hid_driver)
      |                                         ^~~~~~~~~~~~~~~~~~~~~~
/home/USERr/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c:2275:21: note: in expansion of macro ‘wacom_is_using_usb_driver’
 2275 |                 if (wacom_is_using_usb_driver(wacom->hdev)) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c:38:71: error: ‘usb_hid_driver’ undeclared (first use in this function); did you mean ‘to_hid_driver’?
   38 | com_is_using_usb_driver(hdev) hid_is_using_ll_driver(hdev, &usb_hid_driver)
      |                                                             ^~~~~~~~~~~~~~

/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c:2275:21: note: in expansion of macro ‘wacom_is_using_usb_driver’
 2275 |                 if (wacom_is_using_usb_driver(wacom->hdev)) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c:38:71: note: each undeclared identifier is reported only once for each function it appears in
   38 | com_is_using_usb_driver(hdev) hid_is_using_ll_driver(hdev, &usb_hid_driver)
      |                                                             ^~~~~~~~~~~~~~

/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c:2275:21: note: in expansion of macro ‘wacom_is_using_usb_driver’
 2275 |                 if (wacom_is_using_usb_driver(wacom->hdev)) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c: In function ‘wacom_probe’:
/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c:38:71: error: ‘usb_hid_driver’ undeclared (first use in this function); did you mean ‘to_hid_driver’?
   38 | com_is_using_usb_driver(hdev) hid_is_using_ll_driver(hdev, &usb_hid_driver)
      |                                                             ^~~~~~~~~~~~~~

/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.c:2829:13: note: in expansion of macro ‘wacom_is_using_usb_driver’
 2829 |         if (wacom_is_using_usb_driver(hdev)) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:252: /home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5/wacom_sys.o] Error 1
make[3]: *** [Makefile:2037: /home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5] Error 2
make[3]: Leaving directory '/usr/src/kernels/6.3.7-200.fsync.fc37.x86_64'
make[2]: *** [Makefile:43: all] Error 2
make[2]: Leaving directory '/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0/4.5'
make[1]: *** [Makefile:372: all-recursive] Error 1
make[1]: Leaving directory '/home/USER/Downloads/Figuring_out_Wacom/input-wacom-1.0.0'
make: *** [Makefile:307: all] Error 2
Build Failed
[USER@USERinput-wacom-1.0.0]$ 

----------------------------------------------------------------------------------------------------

So its saying, in /input-wacom-1.0.0/4.5/wacom_sys.c:2275, on line 38 and 2275 there's maybe a syntax problem. I'm basically code illiterate, so I don't know how to fix it. I'm pretty sure it is syntax because with the xf86 download, there were several errors that prevented a proper install.

I'm still working on this myself, but if anyone can see anything on those lines that is just wrong, I'd appreciate the assistance.

Thank you.

**Comment by Pinglinux** [comment]
Since you are running 6.3.7-200.fsync.fc37.x86_64, your problem is most likely caused by an issue that was fixed by Jason recently https://github.com/linuxwacom/input-wacom/pull/368. Please clone the code from the current source by:

$ git clone https://github.com/linuxwacom/input-wacom.git
$ cd input-wacom
$ ./autogen.sh

then follow the steps at https://github.com/linuxwacom/input-wacom/wiki/Installing-input-wacom-from-source to build the driver.

**Comment by abyssmal131** [comment]
I did what you said, and I got further. Thanks for that, I was losing my mind trying to figure out what to do, but I run into problems when "loading the module". In /sys/module/wacom*/version, there is no "wacom". I ran the troubleshooting commands from the input-wacom install from source page:

sudo rmmod wacom
sudo rmmod wacom_w8001
sudo modprobe wacom
sudo modprobe wacom_w8001

Which gives me the errors: module wacom is not currently loaded, followed by the wacom w8001 not being loaded.

Also, running:

grep "" /sys/module/wacom*/version

comes up with "No such file or directory", even though its plugged in.

The pen still doesn't do anything. the command:
modinfo wacom | grep version

comes up with:

version:        v2.00-0.49.0.43.g7b934c4
srcversion:     165B0877257EFC51F803239

So, does that mean the kernel driver is loaded?

The command:
libwacom-list-local-devices

Responds with:
- name: 'Wacom Cintiq 16'
  bus: 'usb'
  vid: '0x056a'
  pid: '0x03ae'
  nodes: 
  - /dev/input/event5
  - /dev/input/event4

It seems like everything works, but the module isn't loaded which I assume is why the pen doesn't work. It could be the pen, but what else might it be besides a broken pen because I just don't think the pen doesn't work.

**Comment by Pinglinux** [comment]
Did you run [ if test -x ./autogen.sh; then ./autogen.sh; else ./configure; fi && make && sudo make install || echo "Build Failed" ]

> version: v2.00-0.49.0.43.g7b934c4

tells us that you are running the last version of the driver. Your newly built driver should have v2.00-1.0. in it. Is it possible that you didn't install the newly built driver? You would need to enter your password to install it. Anyway, double check your built and install steps.

In fact, even without the new kernel driver, I think wacom.ko with v2.00-0.49.0.43.g7b934c4 should work for your device.

If your device didn't even move the cursor, it could be a kernel driver issue. In that case, post the output from the dmesg command here. I'll take a look. 

If you just can not calibrate the tablet or can not see the tablet in the "Wacom Tablet" panel under Gnome Settings, that's a Gnome issue.

**Comment by abyssmal131** [comment]
I typed in dmesg and this very long text popped up (I don't know what dmesg is):

*i deleted the results of dmesg because i don't know if they're sensitive. The guy helping me gives commentary on the results lower down.*

**Comment by abyssmal131** [comment]
I think I did get mixed up at some point. I'm going through the steps again now

**Comment by abyssmal131** [comment]
This is what I did:

Previously, I tried inputing this command:

if test -x ./autogen.sh; then ./autogen.sh; else ./configure; fi && make && sudo make install || echo "Build Failed"

Which results in "error: implicit declaration of function " problem from the initial post.

I followed the steps you mentioned:

$ git clone https://github.com/linuxwacom/input-wacom.git
$ cd input-wacom
$ ./autogen.sh

then...

if test -x ./autogen.sh; then ./autogen.sh; else ./configure; fi && make && sudo make install || echo "Build Failed"

I did have to input my password.

I tested the module, with my tablet plugged in, with:

grep "" /sys/module/wacom*/version

The response:

grep: /sys/module/wacom*/version: No such file or directory

I do get a version when I input the other command that the author listed as the command used when your tablet is not plugged in:

modinfo wacom | grep version

Which responds with:

version:        v2.00-0.49.0.43.g7b934c4
srcversion:     165B0877257EFC51F803239

"Your newly built driver should have v2.00-1.0. in it. Is it possible that you didn't install the newly built driver?"

I don't know what this means. Could you clarify?

Again, libwacom seems to be working because the command:

libwacom-list-local-devices

Lists the response:
- name: 'Wacom Cintiq 16'
  bus: 'usb'
  vid: '0x056a'
  pid: '0x03ae'
  nodes: 
  - /dev/input/event5
  - /dev/input/event4

I haven't touched really any xsetwacom settings. I did put a copy of 70-wacom.conf, from the "Configuring X Tutorial", into /etc/X11/xorg.conf.d. There is also a copy of 60.wacom.rules in /etc/udev/rules.d which I added the following line to the bottom of the long list of entries (as I have a cintiq-16):

ATTRS{idVendor}=="056a", ATTRS{idProduct}=="03ae", SYMLINK+="input/tablet-cintiq16"

I can't remember if I added these or they're just there, but these are in /lib/udev/rules.d:

70-wacom.rules
65-libwacom.rules
69-xserver-xorg-input-wacom.rules

I'm pretty sure that's everything I've done.

I hear what you're saying that may be within gnome. There isn't like an "enable/disable pen" button, is there? I watched someone turn that button on in Linux Mint in the Mouse and Touchpad settings, I don't have that, but it really just seems like everything but the pen is working.

**Comment by Pinglinux** [comment]
Ok, from your dmesg output I see your tablet is driven by hid-generic driver, not by wacom driver. Please issue the following commands to see if you get anything:

sudo rmmod wacom
sudo modprobe wacom

Move the pen on the tablet to see if cursor moves.

**Comment by abyssmal131** [comment]
For the following:

sudo rmmod wacom

I get:
rmmod: ERROR: Module wacom is not currently loaded

For the following:
sudo modprobe wacom

I get nothing. Nothing happens.

**Comment by Pinglinux** [comment]
After "sudo modprobe wacom", can you move the cursor with your pen?

**Comment by abyssmal131** [comment]
!!!

**Comment by abyssmal131** [comment]
YES. I. CAN!

**Comment by abyssmal131** [comment]
i could have sworn I input that command.

Its in the troubleshooting steps:

sudo rmmod wacom
sudo rmmod wacom_w8001
sudo modprobe wacom
sudo modprobe wacom_w8001

What the heck

**Comment by abyssmal131** [comment]
dude, do you have a "buy me a coffee"? Make one and I will buy you a coffee
https://www.buymeacoffee.com/

What just happened and if it happens again, what do I do?

**Comment by Pinglinux** [comment]
Ok, now your pen is driven by Wacom kernel driver. Your issue is either in libwacom or in the Gnome Control Center. Please post the issue to libwacom to see if Peter has a suggestion for you.

The coffee is unnecessary. It's my pleasure to support users like you ;).

If you reboot your system and you don't see the issue, you are safe. If you see the issue again, share your dmesg output here again.

**Comment by abyssmal131** [comment]
WOOOOOOO!

Boom baby. BOOM! I'm so happy, thank you.

Um. So, I'll post a link to this issue in libwacom? I'll do that. Thank you again! May your std tests always come up negative.

**Comment by abyssmal131** [comment]
Alright, so I restarted my computer and it doesn't work again. I'm assuming those commands will work again, but I'll post what dmesg spits out first:

*I listed the results of dmesg*

**Comment by abyssmal131** [comment]
Just to verify, I input the following commands again:

sudo rmmod wacom
sudo modprobe wacom

And again, my pen started working. Perhaps its a permissions thing? When I turn on my computer, I have to input my password to run some programs. Maybe wherever the drivers are, its got root privileges and I just have to do this step everytime. I personally don't care. It works, I'm happy.

Also, hotplugging seems to work too - so I can unplug my tablet then plug it back in and it still works. It seems like just restarting requires the commands you provided.

**Comment by Pinglinux** [comment]
I see. The root cause is in the system start/reboot process. You are running a Fedora-like system. Please try the following:

make sure wacom.ko is under "/lib/modules/$(uname -r)/kernel/drivers/hid/", then
update the initramfs by the dracut tool:

https://linuxconfig.org/how-to-build-an-initramfs-using-dracut-on-linux

**Comment by abyssmal131** [comment]
I'll do that and tell you what happens

**Comment by abyssmal131** [comment]
In:

/lib/modules/(Nobara Kernel)/kernel/drivers/hid

There is a:

wacom.ko.xz

There is, however, nothing with the exact name: wacom.ko. In fact, all of the files in .../kernel/drivers/hid are .xz files

**Comment by abyssmal131** [comment]
There is a wacom.ko in:

/usr/lib/modules/(Nobara Kernel)/updates/

**Comment by abyssmal131** [comment]
From the link you sent, the command:

sudo dracut --kver $(uname -r)

or is it

sudo dracut --kver uname -r

??

That should build the initramfs and place it into the /boot directory.

Is build the same as install and/or update?

The other command listed: --install
Perhaps that is appropriate, so:

sudo dracut --install uname -r

But, like I said in the previous message, I'm not sure if the file you mentioned is already where its supposed to be or not.

**Comment by abyssmal131** [comment]
i have to go to sleep, but I'll keep responding to this. I'm going to remove the dmesg comment as its contents may be sensitive. I don't know, but better safe than sorry.

**Comment by Pinglinux** [comment]
Feel free to remove/delete any contents that you don't feel safe to share. I'll need to know more of your system settings to give you the exact steps to fix the issue. Please email me at my gmail account. I have the same user name as it is here.

**Comment by abyssmal131** [comment]
Cool, thanks. I sent you an email.
