### ISSUE TITLE
Version mismatch in dmesg and tablet not working?

### ISSUE THREAD

**Issue by PeriGK** [linuxwacom/input-wacom#39]
Hi there,

My wacom one, stopped working this morning. After a little troubleshooting from my side and attempt to recompile/reinstall drivers, I get the following message when connecting it to my laptop.

```
[   42.627349] hid-generic 0003:045E:07A5.000D: input,hidraw2: USB HID v1.11 Device [Microsoft Microsoft® Nano Transceiver v2.1] on usb-0000:00:14.0-2/input2
[   54.805701] usb 1-1: new full-speed USB device number 10 using xhci_hcd
[   54.957705] usb 1-1: New USB device found, idVendor=056a, idProduct=037a
[   54.957712] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   54.957717] usb 1-1: Product: CTL-472
[   54.957721] usb 1-1: Manufacturer: Wacom Co.,Ltd.
[   54.957725] usb 1-1: SerialNumber: 7HE00L1009789
[   55.010715] wacom: version magic '4.15.0-32-generic SMP mod_unload ' should be '4.15.0-33-generic SMP mod_unload '
[   55.010937] wacom: version magic '4.15.0-32-generic SMP mod_unload ' should be '4.15.0-33-generic SMP mod_unload '
[   55.011495] wacom: version magic '4.15.0-32-generic SMP mod_unload ' should be '4.15.0-33-generic SMP mod_unload '
[   55.011696] wacom: version magic '4.15.0-32-generic SMP mod_unload ' should be '4.15.0-33-generic SMP mod_unload '
```

I am working on ubuntu 18.04 LTS.

Any hint appreciated.

Thanks,
Peri

**Comment by jigpu** [comment]
It looks like your system installed a kernel update. The "input-wacom" kernel driver has to be recompiled and reinstalled after every update, but it looks like what got installed was a stale version.

You'll need to remove the stale files before attempting to recompile/reinstall. You can do this by either running `make clean` inside the input-wacom directory, or by deleting the directory and downloading/extracting a new copy. Once you have a clean working directory, try recompiling and reinstalling again. If you continue to get the "version magic" error after a reboot let us know.

**Comment by PeriGK** [comment]
It worked, many thanks once again Jason :)
