### ISSUE TITLE
List of supported wacom devices

### ISSUE THREAD

**Issue by taras-sereda** [linuxwacom/input-wacom#392]
Hello, this is a great repo!

I'd love to bring back my old Intuos 3 A5 (PTZ-630) so I started to search for an open-source driver with a hope to at least make this tablet usable again on my Linux machine. (sadly, latest official driver for mac os doesn't support my device any more)

Is there anywhere a list of devices supported by this driver? And a more specific question: does this driver support Intuos 3 A5 (PTZ-630)?

God bless open source!

**Comment by Pinglinux** [comment]
Search "PTZ-630" here: https://github.com/linuxwacom/input-wacom/wiki/Device-IDs. It is supported!

**Comment by taras-sereda** [comment]
Nice, thanks a lot!
