### ISSUE TITLE
insmod - could not insert module, invalid module format

### ISSUE THREAD

**Issue by Lexpeartha** [linuxwacom/input-wacom#394]
Executing `sudo insmod 4.5/wacom.ko` started giving:
```
insmod: ERROR: could not insert module 4.5/wacom.ko: Invalid module format
```
which started when I upgraded to `Linux 6.5.5-200.fsync.fc38.x86_64` kernel version

**Comment by Pinglinux** [comment]
Did you rebuild wacom.ko after the upgrade? Your wacom.ko was built for the older kernel.

**Comment by Pinglinux** [comment]
Also, why did you need to load the wacom driver yourself? What was wrong with the system in-box driver?

**Comment by Lexpeartha** [comment]
> Did you rebuild wacom.ko after the upgrade? Your wacom.ko was built for the older kernel.

That fixed it, thank you

> Also, why did you need to load the wacom driver yourself? What was wrong with the system in-box driver?

Not sure, but my device is not recognized unless I execute this command myself on every boot, which is what I've been doing
