### ISSUE TITLE
Possibly broken/missing identification of Huion 1060P

### ISSUE THREAD

**Issue by nicolasfella** [linuxwacom/input-wacom#397]
Note that I don't have access to that tablet myself, I'm merely forwarding findings I got.

See https://discuss.kde.org/t/change-graphic-tablet-orientation-in-wayland/6300 for context.

TL;DR libinput fails to recognize the availability of left-hand mode for the tablet tool but works for the pad.

`libinput list-devices` shows "Device:           HID 256c:006e" for the tool and "Device:           HID 256c:006e Pad" for the pad. The pad seems to be matched correctly, but not the tool.

huion-new-1060-plus.tablet has "DeviceMatch=usb:256c:006e:HID 256c:006e Pen;usb:256c:006e:HID 256c:006e Pad".

My guess here is that removing the "Pen" from the DeviceMatch would fix the match and thus libinput recognizing that the device is reversible. I cannot test that myself though.

Does this make sense or are my assumptions here off?

**Comment by jigpu** [comment]
Based on the linked issue, this sounds like a possible problem with the `digimend-kernel-drivers-dkms-git` kernel driver, not input-wacom (which handles none of the Huion tablets). Specifically, the fact that problem went away after uninstalling the DKMS driver (returning to whatever upstream kernel driver is used) makes me think that the stylus is assigned a different name with those two drivers. The upstream driver probably attaches the "Pen" suffix expected by libwacom, while the DKMS driver does not.

I would recommend filing an issue with either https://github.com/DIGImend/digimend-kernel-drivers/issues to check if the devices are correctly named, or with https://github.com/linuxwacom/libwacom/issues to ask about adding the suffix-less version of the device name to the `DeviceMatch=` line (I'm not sure if that's safe or not off the top of my head -- I know Huion sometimes reuses PIDs...)

Closing this as not an input-wacom issue.
