### ISSUE TITLE
3D pen support

### ISSUE THREAD

**Issue by fakepilot** [linuxwacom/input-wacom#415]
Hello,
I just installed Ubuntu Studio 23.10. Is there a way to make my 3D pen work?
At the moment, the extra button does a "BACK" command and I find no way to re-program it.

**Comment by Pinglinux** [comment]
Hi @fakepilot I believe that's an issue with the latest Gnome "Wacom Tablet" feature. I am sure Gnome team is working on that.

**Comment by Pinglinux** [comment]
This project is for Wacom kernel driver. Since you are facing a button configuration issue, it should be a configuration UI issue.
