### ISSUE TITLE
Huion HS64 not working.

### ISSUE THREAD

**Issue by Vidyut** [linuxwacom/input-wacom#422]
Ubuntu 24.04 fresh install. New laptop. Working Huion HS64.

Attaching the tablet doesn't show up any configuration options in settings, but moving the pen moves the mouse.

Tried this as a hack. https://github.com/juansegaes/HS64 Pen started working. Express keys on tablet still don't work.

Downloaded and installed Huion official driver. Expresskeys can be assigned, but still don't work. Uninstalled the driver because it fixes the tablet to screen proportions with no way to use it like a touchpad.

Same tablet is working normally with Ubuntu 22.04. I checked, and it doesn't have a tablet file for HS64 either, but seems to recognise it as a H950p - which should have a lot more features that mine doesn't, but it doesn't matter, as the tablet works normally. I didn't even know it wasn't recognised properly until I had a problem now.

I suspect there's some tiny fix somewhere that I could do and put myself out of my misery, but no clue what.

**Comment by Pinglinux** [comment]
This project is for kernel driver. Your issue is either in libwacom or Gnome. Please check out libwacom to see if your device is supported or not.
