### ISSUE TITLE
Pen is not working in fullscreen

### ISSUE THREAD

**Issue by cankurttekin** [linuxwacom/input-wacom#433]
I am using Lenovo Yoga 7i 14irl8, 
![Screenshot from 2024-07-18 22-24-50](https://github.com/user-attachments/assets/c567f575-f61d-4f0f-8b2a-d7329dfc85f5)

when i open apps in fullscreen mode pen only works if i dont lift up, as long as i lift up the pen once it does not take inputs if i dont quit from fullscreen. 
I tried observing events with `libinput debug-events --verbose` and it detecs my pen inputs even on fullscreen mode but none of my application takes it.
 event5   TABLET_TOOL_AXIS        +2.203s		192.35*/90.68*	tilt: 0.00/0.00	pressure: 0.00

libinput list-devices output:
```

`Device:           Wacom HID 5362 Pen
Kernel:           /dev/input/event5
Group:            6
Seat:             seat0, default
Size:             302x188mm
Capabilities:     tablet 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   none
Rotation:         n/a

Device:           Wacom HID 5362 Finger
Kernel:           /dev/input/event6
Group:            6
Seat:             seat0, default
Size:             302x188mm
Capabilities:     touch 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0
`


```

**Comment by flynx** [comment]
Hi,

Got exactly the same issue, with mostly the same stack:
_Lenovo ThinkPad X1 Yoga 3rd
Fedora Linux 40 (Workstation Edition)
Linux 6.9.8-200.fc40.x86_64 x86_64
Wayland
GNOME Shell 46.3.1_

And I also noticed that the pen input does not work iff the app covers the top left corner of the screen (or is within 20-50 pixels from it), an as long as the corner is not covered everything works.


journalctl reports when pen is not working:
```
Jul 23 04:13:07 x1f kernel: wacom 0003:056A:5146.0003: wacom_idleprox_timeout: tool appears to be hung in-prox. forcing it out.
```


libinput list-devices:
```
libinput-config: configuring device 'Wacom Pen and multitouch sensor Finger'
Device:           Wacom Pen and multitouch sensor Finger
Kernel:           /dev/input/event5
Group:            5
Seat:             seat0, default
Size:             309x174mm
Capabilities:     touch 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         0.0

libinput-config: configuring device 'Wacom Pen and multitouch sensor Pen'
Device:           Wacom Pen and multitouch sensor Pen
Kernel:           /dev/input/event7
Group:            5
Seat:             seat0, default
Size:             309x174mm
Capabilities:     tablet 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   none
Rotation:         n/a
```

**Comment by cankurttekin** [comment]
i am not sure but this is probably gnome and wayland thing. i have dual boot with gnome 42 and it does work perfectly on that. we might open this issue on gnome vcs

**Comment by OlaszPL** [comment]
> i am not sure but this is probably gnome and wayland thing. i have dual boot with gnome 42 and it does work perfectly on that. we might open this issue on gnome vcs

[https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7812](url)

**Comment by flynx** [comment]
@OlaszPL everything worked for me several updates back as well, but I can't exactly say when things broke and on what exact package update.

**Comment by cankurttekin** [comment]
> @OlaszPL everything worked for me several updates back as well, but I can't exactly say when things broke and on what exact package update.

Is it possible to you to find what is latest working version?

**Comment by OlaszPL** [comment]
I downgraded gnome-shell to 46.0-1 and libwacom to 2.10.0-1 but it didn't work.

**Comment by cankurttekin** [comment]
Yeah i also tried that. It works on 44, but i am not sure about 45, will chek that.

**Comment by flynx** [comment]
I have everything working on Gnome 45.5 but that's not a clean test -- different hardware.

**Comment by OlaszPL** [comment]
[https://gitlab.gnome.org/GNOME/mutter/-/issues/3616](https://gitlab.gnome.org/GNOME/mutter/-/issues/3616)
This issue was closed 2 weeks ago, so we just have to wait for a new mutter release.
It appears that this fix is included in mutter 47 that would probably be released with Gnome 47.

**Comment by cankurttekin** [comment]
> https://gitlab.gnome.org/GNOME/mutter/-/issues/3616 This issue was closed 2 weeks ago, so we just have to wait for a new mutter release. It appears that this fix is included in mutter 47 that would probably be released with Gnome 47.

thanks for the info
