### ISSUE TITLE
Wacom Intuos M (Medium) BT (Bluetooth): When Connected through Bluetooth, No Recognition

### ISSUE THREAD

**Issue by CoolBeans90** [linuxwacom/input-wacom#439]
**Context Summary:**
1) The Wacom Intuos M BT (Model: CTL-6100WL) connected through USB works well
2) The Wacom Intuos M BT connected through Bluetooth does not work
    --> Applications (i.e., Xournal++ and GIMP), Gnome Control Center (i.e., Wacom Tablet Finder), and xsetwacom do not detect the Wacom Intuos M BT when it is connected through Bluetooth

**Note #1:** Even though I have been using Linux since 2015, I have not had enough time to really, deeply learn Linux, so consider me a Level 0 Beginner.  Please and Thank you.    

**Generated File after runnign sysinfo.sh (Generation Date: 9/6/2024):**
1) Without the Wacom Intuos M BT connected at all (i.e., no USB or BT connection): [sysinfo.gWmDcbLJm5.tar.gz](https://github.com/user-attachments/files/16912317/sysinfo.gWmDcbLJm5.tar.gz)

2) With the Wacom Intuos M BT connected through BT:
[sysinfo.CKBno6pPaU.tar.gz](https://github.com/user-attachments/files/16912465/sysinfo.CKBno6pPaU.tar.gz)

**Generated dmesg file (Generation Date: 9/6/2024):**
1) With the Wacom Intuos M BT connected through BT: [DMESG_9-6-2024_withBTConnect.txt](https://github.com/user-attachments/files/16912523/DMESG_9-6-2024_withBTConnect.txt)
  -->Uncertain if there is enough information in the .txt file from dmesg
  -->Let me know if more data is needed

**Other Info:**
After running hostnamectl:
![image](https://github.com/user-attachments/assets/358f362a-bd99-4e84-ac3f-d575bb08d082)
  -->XFCE or Xubuntu
![image](https://github.com/user-attachments/assets/9c345983-67a2-4e73-8065-42ead68f545e)

![image](https://github.com/user-attachments/assets/69159403-2934-417e-9148-4bbaabfd3d37)
  -->Not sure why this command is not working now
  -->It was working earlier today (9/6/2024)
     --->I was able to determine that I am running under the X11 enviroment

I have built from source the following:
1) xf86-input-wacom-1.2.2
  -->Reason for building from source: Wacom Intuos M BT connected through Bluetooth did not work with what was installed previously through 'apt-get install' from the standard Ubuntu respositories or automatically was 
2) input-wacom-1.3.0
  -->Same reason as 1)

**Note #2:**  I have also looked at 'Closed' issues that were similar, but did not find anything that could help me with my current situation.

If there is any further information you need or feedback you have (i.e., questions, concerns, suggestions, etc.), please let me know. 

Thank you.

**Comment by CoolBeans90** [comment]
#371 is a similar 'Closed' issue.  From what I gathered, please correct me if I am incorrect, it appears the patch or correction was included or backported in Linux Kernel 4.5 and into input-wacom (whatever the version was at the time).

**While Wacom Intuos M BT was connected through BT:**
![image](https://github.com/user-attachments/assets/88877849-f33b-4999-b002-50fb455e2130)
  -->Command was run right before 'bluetoothctl info"
    --->See below image

![image](https://github.com/user-attachments/assets/cf3ca856-79d3-4663-8f26-558b81bc4c20)
  -->Also, it appears random that upon initial connection with bluetooth, the Wacom Intuos M BT fails to connected because the socket fails to establish
  -->Either immediately after the initial attempt connect or a few times after, then the Wacom Intuos M BT will have a successful connection

**Generated dmesg file (Generation Date: 9/6/2024) at around 2:12pm (PST):**
[DMESG_9-6-2024_2-12pm_withBTConnect.txt](https://github.com/user-attachments/files/16912952/DMESG_9-6-2024_2-12pm_withBTConnect.txt)

**Comment by CoolBeans90** [comment]
I am closing this issue becuase I exchanged the Wacom Intuos M BT (Model: CTL-6100WL) for a XP-Pen Deco LW.  However, anyone who has a similar issue can hopefully use this issue for reference and as a template to report a similar issue.

**Note:** This issue has not been resolved.

**Comment by sbrl** [comment]
Yes, I have this issue with the #445 branch of input-wacom, but not only with bluetooth but wired as well.
