### ISSUE TITLE
I get the build failed error

### ISSUE THREAD

**Issue by NoahDaChonkyCat** [linuxwacom/input-wacom#441]
-bash: ./configure: No such file or directory
Build Failed

everytime i put the line of code:
mcalafd21@penguin:~$ if test -x ./autogen.sh; then ./autogen.sh; else ./configure; fi && make && sudo make install || echo "Build Failed"

and yeah im using my highschool laptop cause why not get the wacom registered there :D 
Ill appreciate alot help! <3

**Comment by jigpu** [comment]
Based on the `mcalafd21@penguin:~$` prompt, it seems that your terminal is currently inside the home (`~`) directory. Once you've downloaded and extracted the .tar.gz source files, you'll need to use the `cd` command to have your terminal enter the "input-wacom" directory.
