### ISSUE TITLE
Intuos BT S works via Bluetooth

### ISSUE THREAD

**Issue by EverfreeFaerie** [linuxwacom/input-wacom#45]
I recently bought an Intuos BT S (CTL-4100WL) and connected to it via a Bluetooth 4.0 adapter. Pointing, buttons and pressure sensitivity worked for me. The „Device IDs“ wiki page states that it only works (or is tested?) via USB. Should that be added there?

Linux: 4.18.9
libwacom: 0.30
`modinfo wacom` yields version V2.00 and srcversion 52EA4FCCDDA2584FF8C195E
(xf86-input-wacom is not installed)

**Comment by jigpu** [comment]
Looks like that was a typo on our part. The 4100WL appears twice on the page: the first one under the "USB Peripherals" heading is for its USB interface and the second one under "Bluetooth Peripherals" *should have said* it was for the Bluetooth interface. I've edited the wiki to fix this. Thanks!
