### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by carlcheunghk** [linuxwacom/input-wacom#47]
I have been getting the following error after installing input-wacom on my Ubuntu 18.04

```
Err:16 http://ppa.launchpad.net/doctormo/wacom-plus/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/doctormo/wacom-plus/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

```
So now, I would like to remove everything related, but I cannot find relevant instructions. Do I just reverse my installation process by replacing 'install' with 'uninstall'? Please help, thanks!

**Comment by jigpu** [comment]
To answer the question: yes `make uninstall` should undo the process of running `make install` from our driver.

That said, the issue you're seeing should be unrelated to the installation of *our* driver. Rather, it seems to be an issue with the (third-party) *wacom-plus PPA*. Specifically, the error is informing you that the PPA doesn't have any packages available for Ubuntu 18.04, and that Ubuntu therefore can't safely install updates.

The "wacom-plus" PPA only has *very* old versions of our driver (it was last updated in 2015). Its drivers are actually older than what is are shipped with Ubuntu 18.04... I would recommend removing the PPA from your system: try using [these instructions](https://linuxconfig.org/how-to-list-and-remove-ppa-repository-on-ubuntu-18-04-bionic-beaver-linux) to do so. After doing so and rebooting, if your tablet doesn't work, try downloading and installing our driver from here on Github.
