### ISSUE TITLE
How to remove input-wacom from Ubuntu 18.04?

### ISSUE THREAD

**Issue by carlcheunghk** [linuxwacom/input-wacom#51]
I wanted to buy a wacom tablet and installed input-wacom driver to my Ubuntu 18.04
But then I changed my mind and don't want to buy it now.

I found that every time I use
`sudo apt-get update`
I get the following error from wacom driver.
`Err:16 http://ppa.launchpad.net/doctormo/wacom-plus/ubuntu bionic Release      
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/doctormo/wacom-plus/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
Please tell me how to remove this driver. Do I just reverse the installation process? I am not sure I know how to do this, please help, thanks!

**Comment by jigpu** [comment]
As mentioned in #47, you should be able to remove the doctormo PPA by following the instructions at https://linuxconfig.org/how-to-list-and-remove-ppa-repository-on-ubuntu-18-04-bionic-beaver-linux
If those instructions don't work, let us know.
