### ISSUE TITLE
 Wacom STU-530 not supported

### ISSUE THREAD

**Issue by n0n1ck87** [linuxwacom/input-wacom#52]
[ 2632.678391] usb 3-1: new full-speed USB device number 5 using xhci_hcd
[ 2632.860539] usb 3-1: New USB device found, idVendor=056a, idProduct=00a5
[ 2632.860544] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2632.860548] usb 3-1: Product: STU-530
[ 2632.860551] usb 3-1: Manufacturer: Wacom Co.,Ltd.
[ 2632.860553] usb 3-1: SerialNumber: 7DZQ008370
[ 2632.949532] input input30: Absolute device without dev->absinfo, refusing to register
[ 2632.949560] wacom: probe of 0003:056A:00A5.0007 failed with error -22

**Comment by jigpu** [comment]
None of the STU series of tablets are supported by the input-wacom driver at this time. If you're a developer, you can try to add support for this tablet to input-wacom or register for a developer account at Wacom and make use of their [STU SDK for Linux](https://developer-docs.wacom.com/display/DevDocs/STU+SDK+-+Linux).
