### ISSUE TITLE
Express keys not configurable on Wacom Mobile Studio Pro in NixOS

### ISSUE THREAD

**Issue by Fresheyeball** [linuxwacom/input-wacom#58]
Everything works great! Except for this one bit, where the express keys don't work

Here is the tarball requested on twitter [sysinfo.KcY0YghStv.tar.gz](https://github.com/linuxwacom/input-wacom/files/2681277/sysinfo.KcY0YghStv.tar.gz)

```
> xsetwacom --list
Wacom MobileStudio Pro 13 Touch Finger touch	id: 12	type: TOUCH     
Wacom MobileStudio Pro 13 Pen stylus	id: 11	type: STYLUS    
Wacom MobileStudio Pro 13 Pen eraser	id: 16	type: ERASER  
```

/run/current-system/sw/lib/udev/rules.d/wacom.rules
```
ACTION!="add|change", GOTO="wacom_end"

# Match all serial wacom tablets with a serial ID starting with WACf
# Notes: We assign NAME though we shouldn't, but currently the server requires it
#        We assign the lot to subsystem pnp too because server reads NAME from
#        the parent device. Once all that's fixed, as simple SUBSYSTEM="tty"
#        will do and the ENV{NAME} can be removed.
SUBSYSTEM=="tty|pnp", SUBSYSTEMS=="pnp", ATTRS{id}=="WACf*", ENV{ID_MODEL}="Serial Wacom Tablet $attr{id}", ENV{ID_INPUT}="1", ENV{ID_INPUT_TABLET}="1", ENV{NAME}="Serial Wacom Tablet $attr{id}"
SUBSYSTEM=="tty|pnp", SUBSYSTEMS=="pnp", ATTRS{id}=="FUJ*", ENV{ID_MODEL}="Serial Wacom Tablet $attr{id}", ENV{ID_INPUT}="1", ENV{ID_INPUT_TABLET}="1", ENV{NAME}="Serial Wacom Tablet $attr{id}"

# comment out the next line if your distribution does not provide systemd
# If a /dev/ttySx device with the WACf name is detected, start the
# wacom-inputattach service with the kernel name as parameter
SUBSYSTEM=="tty|pnp", KERNEL=="ttyS[0-9]*", ATTRS{id}=="WACf*", TAG+="systemd", ENV{SYSTEMD_WANTS}+="wacom-inputattach@%k.service"

LABEL="wacom_end"
```

![2018-12-14-112337_1804x1048_scrot](https://user-images.githubusercontent.com/609279/50020297-cd54e080-ff92-11e8-9c69-13eea1fb4df5.png)

**Comment by jigpu** [comment]
Your journalctl log has the following lines in it, which indicate that the X server doesn't know what driver to use:
~~~
(II) config/udev: Adding input device Wacom MobileStudio Pro 13 Pad (/dev/input/event18)
(II) No input driver specified, ignoring this device.
(II) This device may have been added with another device file.
~~~
Normally there are configuration files under `/usr/share/X11/xorg.conf.d` that (among other things) tell X what drivers to use for specific devices. You can also have an `/etc/X11/xorg.conf.d` directory that contains user-supplied overrides. The former is missing, and the latter seems to only have empty files?

It looks like NixOS is using some magic to place the configuration files elsewhere. Thankfully the journalctl logs point out exactly where things are hiding:
~~~
(++) Using config file: "/nix/store/xq1r0x9c36sjdmjansvh92icb4vssycm-xserver.conf"
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/nix/store/6040ggimcbc6cvbv7hky06al9hdrfi9w-xorg-server-1.19.6/share/X11/xorg.conf.d"
~~~
Could you please put each of those configuration files and directories into a tarball and upload it here? If the configuration files don't properly specify the Wacom driver, that would definitely explain why/how the pen is working fine for you but not the expresskeys.

**Comment by Fresheyeball** [comment]
[config.tar.gz](https://github.com/linuxwacom/input-wacom/files/2681523/config.tar.gz)

**Comment by jigpu** [comment]
How odd... That tarball is still (somehow) missing configuration information. Can you try running `sudo cat /etc/X11/xorg.conf.d/70-wacom.conf` and pasting the output here? That file is 0 bytes in size in the tarball, but pretty much *has* to be where some of the missing configuration data lives*. Maybe its only readable by root and that's why it's showing up as a 0-byte file? If nothing is printed out by cat, provide the output from `ls -l /etc/X11/xorg.conf.d` for me.

*The only other option I can think of is a config file hiding (and being silently loaded?!?) under `/nix/store/nmhrf6zcr8df2s8clzsiazknymflrb96-xf86-input-wacom-0.36.0/`

**Comment by Fresheyeball** [comment]
```
# Some of the below input classes appear 3x times, once for each of
# "tablet", "touchscreen", and "touchpad" to ensure that the Wacom
# driver is not accidentally bound to other types of hardware that
# Wacom has made which are not handled by the wacom driver (e.g the
# Wacom Bluetooth Keyboard)
#
# https://sourceforge.net/p/linuxwacom/bugs/294/

Section "InputClass"
        Identifier "Wacom USB tablet class"
        MatchUSBID "056a:*"
        MatchDevicePath "/dev/input/event*"
        MatchIsTablet "true"
        Driver "wacom"
EndSection

Section "InputClass"
        Identifier "Wacom USB touchscreen class"
        MatchUSBID "056a:*"
        MatchDevicePath "/dev/input/event*"
        MatchIsTouchscreen "true"
        Driver "wacom"
EndSection

Section "InputClass"
        Identifier "Wacom USB touchpad class"
        MatchUSBID "056a:*"
        MatchDevicePath "/dev/input/event*"
        MatchIsTouchpad "true"
        Driver "wacom"
EndSection

Section "InputClass"
	Identifier "Wacom tablet class"
	MatchProduct "Wacom|WACOM|PTK-540WL|ISD-V4"
	MatchDevicePath "/dev/input/event*"
	MatchIsTablet "true"
	Driver "wacom"
EndSection

Section "InputClass"
	Identifier "Wacom touchscreen class"
	MatchProduct "Wacom|WACOM|PTK-540WL|ISD-V4"
	MatchDevicePath "/dev/input/event*"
	MatchIsTouchscreen "true"
	Driver "wacom"
EndSection

Section "InputClass"
	Identifier "Wacom touchpad class"
	MatchProduct "Wacom|WACOM|PTK-540WL|ISD-V4"
	MatchDevicePath "/dev/input/event*"
	MatchIsTouchpad "true"
	Driver "wacom"
EndSection

# Serial Wacom devices should always be one of tablet, touchscreen, or
# touchpad so we can safely get away with just one match section in
# these cases
Section "InputClass"
        Identifier "Wacom PnP device class"
        MatchPnPID "WACf*|WCOM*|WACM*|FUJ02e5|FUJ02e7|FUJ02e9"
        MatchDevicePath "/dev/input/event*"
        Driver "wacom"
EndSection

Section "InputClass"
	Identifier "Wacom serial class"
	MatchProduct "Serial Wacom Tablet"
	Driver "wacom"
EndSection

Section "InputClass"
        Identifier "Wacom serial class identifiers"
        MatchProduct "WACf|FUJ02e5|FUJ02e7|FUJ02e9"
        Driver "wacom"
EndSection

# Hanwang tablets
Section "InputClass"
	Identifier "Hanwang class"
	MatchProduct "Hanwang"
	MatchDevicePath "/dev/input/event*"
	Driver "wacom"
EndSection

# Waltop tablets
Section "InputClass"
	Identifier "Waltop class"
	MatchProduct "WALTOP"
	MatchIsTablet "on"
	MatchDevicePath "/dev/input/event*"
	Driver "wacom"
EndSection

# N-Trig Duosense Electromagnetic Digitizer
Section "InputClass"
	Identifier "Wacom N-Trig class"
	MatchProduct "HID 1b96:0001|N-Trig Pen|N-Trig DuoSense"
	MatchDevicePath "/dev/input/event*"
	Driver "wacom"
	Option "Button2" "3"
EndSection

# Dell Canvas 27 (touch part is an Advanced Silicon, pen part a Wacom)
Section "InputClass"
        Identifier "Dell Canvas 27 Touch"
        MatchUSBID "2575:0204"
        MatchDevicePath "/dev/input/event*"
        MatchIsTouchscreen "true"
        Driver "wacom"
EndSection
```

**Comment by Fresheyeball** [comment]
[config.tar.gz](https://github.com/linuxwacom/input-wacom/files/2681671/config.tar.gz)
This one should work

**Comment by pinktrink** [comment]
You're correct that NixOS uses a lot of magic, it's pretty much symlinks all the way down, so the original tarball didn't work because `h` wasn't used to dereference symlinks.

**Comment by jigpu** [comment]
Thanks for that tidbit @pinktrink and the updated tarball @Fresheyeball!

The configuration files look sane so the next place to look would be towards udev. All of the configuration rules have predicates like "MatchIsKeyboard" or "MatchIsTablet", and the way Xorg evaluates that information is by looking at udev tags. In particular, we need to make sure that `ID_INPUT_TABLET=1` and `ID_INPUT_TABLET_PAD=1` are being set. You should be able to run ` udevadm info -q all /dev/input/event18` to get a dump of the current udev tags for the pad device -- please paste its output here.

The necessary udev rules are normally shipped as part of the "libwacom" package and installed to `/usr/lib/udev/rules.d/65-libwacom.rules`. I'm not entirely sure where this would be located on your system. You could try `find / -name 65-libwacom.rules 2> /dev/null` or see if maybe the path `/nix/store/1diklgcjhmvcxi9p1ifp6wcnyr6k7z9jhrlzfhzjqd6zipk01slw-libwacom-0.29` exists on your system (or perhaps `/nix/store/0qjd4bn2abwzic34cm0sw3srx02spszbsvfdbzbpn2cb62b5gjmw-libwacom-0.31` if https://nixos.org/nixos/packages.html#libwacom is leading me astray?). If you can find the "65-libwacom.rules" file, attach it here for review.

**Comment by Fresheyeball** [comment]
@jigpu I posted my rules in the op. Here it is again for good measure

cat /run/current-system/sw/lib/udev/rules.d/wacom.rules 
```
ACTION!="add|change", GOTO="wacom_end"

# Match all serial wacom tablets with a serial ID starting with WACf
# Notes: We assign NAME though we shouldn't, but currently the server requires it
#        We assign the lot to subsystem pnp too because server reads NAME from
#        the parent device. Once all that's fixed, as simple SUBSYSTEM="tty"
#        will do and the ENV{NAME} can be removed.
SUBSYSTEM=="tty|pnp", SUBSYSTEMS=="pnp", ATTRS{id}=="WACf*", ENV{ID_MODEL}="Serial Wacom Tablet $attr{id}", ENV{ID_INPUT}="1", ENV{ID_INPUT_TABLET}="1", ENV{NAME}="Serial Wacom Tablet $attr{id}"
SUBSYSTEM=="tty|pnp", SUBSYSTEMS=="pnp", ATTRS{id}=="FUJ*", ENV{ID_MODEL}="Serial Wacom Tablet $attr{id}", ENV{ID_INPUT}="1", ENV{ID_INPUT_TABLET}="1", ENV{NAME}="Serial Wacom Tablet $attr{id}"

# comment out the next line if your distribution does not provide systemd
# If a /dev/ttySx device with the WACf name is detected, start the
# wacom-inputattach service with the kernel name as parameter
SUBSYSTEM=="tty|pnp", KERNEL=="ttyS[0-9]*", ATTRS{id}=="WACf*", TAG+="systemd", ENV{SYSTEMD_WANTS}+="wacom-inputattach@%k.service"

LABEL="wacom_end"
```

**Comment by jigpu** [comment]
Ah, okay. Was hoping there were more rules than that because the "wacom.rules" file that you posted doesn't have the necessary rules to set up the IDs -- only "65-libwacom.rules" does.

If that's the case then it's a packaging issue in NixOS and they need to start shipping the additional rules.

You can try downloading the Ubuntu package from https://packages.ubuntu.com/cosmic/all/libwacom-common/download and extracting the 65-wacom.rules file. I'm not entirely sure where you'd need to place it on your system for it to be loaded, but maybe there's some docs on how to write custom rules for NixOS that specia specify a location.

**Comment by pinktrink** [comment]
Additional udev configuration can be placed in /etc/nixos/configuration.nix so I'll try putting it there.

**Comment by pinktrink** [comment]
After grabbing relevant configuration from 65-libwacom.rules, everything is working perfectly. Appreciate it!

**Comment by Pinglinux** [comment]
It's a NixOS issue, not ours.
