### ISSUE TITLE
[RESOLVED] Intuos Pro 5 Medium /dev/input devices disappearing on Raspberri Pi Zero

### ISSUE THREAD

**Issue by nebularnoise** [linuxwacom/input-wacom#60]
_______________________
FIX:
-----
**I'm using a USB3 hub with a Raspberry Pi**, this is a [known issue](https://www.raspberrypi.org/documentation/hardware/raspberrypi/usb/README.md#knownissues) of USB3 Hubs not enumerating devices. I realised halfway through writing this issue, but I'm leaving this here at it might help someone else.
_______________________

CONTEXT:
-----
I'm trying to read my Intuos Pro 5 tablet's coordinates, plugged through USB to a Raspberry Pi Zero running the latest Raspbian Lite. I updated the kernel to 4.14.90+ with rpi-update. I installed `libwacom2` with apt-get after my trouble started.

When I plug the tablet I get the following:
```sh
pi@raspberrypi:~ $ lsusb
Bus 001 Device 005: ID 0bda:8153 Realtek Semiconductor Corp.
Bus 001 Device 025: ID 056a:0357 Wacom Co., Ltd
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
pi@raspberrypi:~ $ libwacom-list-local-devices
Failed to find any devices.
pi@raspberrypi:~ $ ls /dev/input
mice
```

However, *sometimes*, seemingly at random, a combination of the following make the event devices appear:
- unplugging the device and plugging it again
- waiting a few minutes before plugging it again
- rebooting
- `sudo modprobe wacom`
- Plugging the tablet in a windows computer before plugging it again

When the devices appear, I have around 30 seconds before the devices disappear again. During that time, I get:
```sh
pi@raspberrypi:~ $ ls /dev/input
by-id  by-path  event0  event1  js0  mice  mouse0
```
Or sometimes the same output with `event2`as well.

Inspecting one device seems to stabilise its presence as long as it emits events. For example:
 `evemu-record /dev/input/event2` shows me the events as expected,  **as long as I keep moving my finger on the tablet** but if I stop causing events (by removing my finger from the surface of the tablet), it seems to cause a crash (`error: could not record device`). Then I can do this:
```sh
pi@raspberrypi:~ $ ls /dev/input
mice        event2
```
For a few seconds after the crash, I can still access `/dev/input/event2`, but it ultimately disappears after that time.

**Comment by jigpu** [comment]
Thanks for the heads-up!
