### ISSUE TITLE
Installing input wacom from source Build / Install "Build Failed" Error

### ISSUE THREAD

**Issue by BlobOfAwe** [linuxwacom/input-wacom#61]
I'm trying to set up my Wacom Intuos S with my Linux Mint computer.

OS: Linux Mint 18.1 Cinamon 64-bit
Linux Kernel: 4.4.0-53-generic

Followed the steps to install the 'input-wacom' pack, reached the Build/Install command, it returned 'Build Failed'

The tutorial says to ask the devs for help, but I'm not sure who to ask, so I'm here.

I'm new to programming, so please don't dump a bunch of techy lingo on me in the solution. The simpler the better.

**Comment by jigpu** [comment]
Can you please copy/paste the full output from the terminal when running the install steps? We'll need this to understand what part failed.

**Comment by BlobOfAwe** [comment]
$ if test -x ./autogen.sh; then ./autogen.sh; else ./configure; fi && make && sudo make install || echo "Build Failed"
bash: ./configure: No such file or directory
Build Failed
`

**Comment by jigpu** [comment]
Thanks! Did you run the command inside the extracted input-wacom directory? Could you run `ls -l` inside the directory for me so I can see what files are missing? Either the configure or autogen.sh script should be there...

**Comment by BlobOfAwe** [comment]
Oh pfft. I forgot to download and extract the directory, that's why it wasn't working.

I extracted it and re-ran the program inside the directory and it works fine now. I just didn't read the instructions properly. Thanks for helping me though!

**Comment by jigpu** [comment]
Glad it was something simple :) Hope the rest is smooth sailing.
