### ISSUE TITLE
Pen stays in the "clicked" state as soon as it's connected, unless.I change the threshold

### ISSUE THREAD

**Issue by EternityForest** [linuxwacom/input-wacom#62]
I'm using a Wacom Bamboo, which works flawlessly if I set the threshold to 170 in the xorg conf, which was just a guess. I haven't tested to see what the lowest working value is. 

A few others have reported this problem, and I had a similar issue on an XP-Pen that's now packed away somewhere.

If this is common enough, would it make sense to either increase the default threshold, or run a self calibration where the threshold is set just above whatever the lowest value ever detected is, so that just hovering the pen won't be seen as a click?

I had the same issue, with the same fix on Mint, and Kubuntu. My Wacom was used when I got it, so there may be some kind of calibration drift.

Thanks a bunch guys!

**Comment by jigpu** [comment]
I believe the driver is supposed to compensate for this automatically. If it enters proximity with a non-zero pressure value, it should take that value to be the real zero point so that the threshold works properly. I'm not sure why this wouldn't be working in your case... I'll have to do some digging...

**Comment by EternityForest** [comment]
It could be that there's enough noise in the pressure reading in high EMI
areas that the noise pushes it above the zero point.

**Comment by jigpu** [comment]
Please try running the [capture.sh script](https://gist.githubusercontent.com/jigpu/b7b47e4bede584cec8562f666fd84af4/raw/1050d9aab9514ca0658c3cb415ccb11af5e4d6d6/capture.sh) to record what's going on. When you first run it, you'll probably be asked to install a few of its dependencies. Once they've been installed you should be asked to select a device -- choose the "stylus" device. Next, bring the pen in and out of prox a few times (without touching the pen to the surface) to be sure that the issue has been captured. Finally, hit CTRL+C and attach the generated tarball to this issue.

This should let us see the events that are sent by the device and our driver to narrow down where it comes from. E.g., a hardware issue, EMI (which has been known to cause occasional problems), or one of the software layers.

EDIT: Added link to capture script

**Comment by EternityForest** [comment]
Allright, here ya go! I don't know if it matters, but this is *with* the xorg.conf and the modifed threshold.
[record_1547507083.tar.gz](https://github.com/linuxwacom/input-wacom/files/2757391/record_1547507083.tar.gz)

**Comment by jigpu** [comment]
Thanks! Those logs indicate that the hardware reported zero pressure at all times, aside from a brief moment (t=9.60 to t=9.71). The pressure values reported at this time were much higher than I would normally expect for interference (nearly 5% of full-scale). I don't see any indication that the pen would have been clicked at any other time in the log.

Could you re-run the capture script without the custom threshold set?

**Comment by Pinglinux** [comment]
xf86-input-wcom or libinput, whichever is used, takes case of initial non-zero pressure issue. The issue can be fixed by replacing the worn-out pen tip with a new one.
