### ISSUE TITLE
Everything but eraser works on Nuvision Solo 10 Draw

### ISSUE THREAD

**Issue by ShapeShifter499** [linuxwacom/input-wacom#69]
I don't know much about kennel code. But I'm hoping someone here can help me out.  @jigpu I saw that you made quite a few updates and changes to the kennel driver. Maybe you could help me out or point me to someone who could? @whot mentioned it could be a driver issue. That whole discussion is here: https://github.com/linuxwacom/libwacom/issues/70

This is the only major issue left for this tablet, everything else works pretty good under Linux.
EDIT: Except built-in cameras, but I wasn't buying this tablet for the camera anyways.

**Comment by ShapeShifter499** [comment]
Any updates on this?

**Comment by whot** [comment]
As mentioned in https://github.com/linuxwacom/libwacom/issues/70, the driver used here is `hid-generic`, not the wacom driver. So the input-wacom project is kinda the wrong project here since it focuses exclusively on wacom tablets, sorry.

**Comment by ShapeShifter499** [comment]
@whot wait, this is a "hid-generic" issue?
