### ISSUE TITLE
Drivers not loading after I reboot.

### ISSUE THREAD

**Issue by terrestrian** [linuxwacom/input-wacom#73]
I am running OpenSUSE Tumbleweed and using Huion H640P. I installed the drivers from source using make. Problem is whenever I reboot my system, drivers doesn't work. To get things done I need to type;

1. `sudo modprobe -r hid-kye hid-uclogic hid-polostar hid-viewsonic` from terminal.

And re-plug my tablet manually.

I mean they work in the end but I don't want to do these steps every time I need to use my tablet.

Btw, I checked my dmesg and it gives this error everytime.

>[   20.875947] uclogic 0003:256C:006E.0001: device parameters not found
>[   20.875953] uclogic 0003:256C:006E.0001: tablet enabling failed

**Comment by jigpu** [comment]
The input-wacom drivers are not used by Huion devices, and the driver is not one of those listed in your command. I would [file a DIGImend bug](https://github.com/DIGImend/digimend-kernel-drivers/issues) since I believe that is where development of the mentioned "uclogic" driver is done.
