### ISSUE TITLE
links to protocol descriptions are broken

### ISSUE THREAD

**Issue by reuvenpo** [linuxwacom/input-wacom#85]
The links under:

https://github.com/linuxwacom/input-wacom/wiki/Wacom-Protocols

... lead to removed pages in the old sourceforge wiki. I can't find any equivalent information online.

Can you please update those links if the relevant information is still available?

EDIT: i can find the old versions of the pages under https://web.archive.org/

**Comment by skomra** [comment]
Hi reuvenpo,

There is an archive of the final state of the old wiki available at: https://github.com/jigpu/linuxwacom-wiki-archive/tree/master/wiki . Those pages contain very old information so I did not transfer them over when I migrated the wiki.

I have updated the broken links that you point out with their equivalent page from the archive.

Best,
Aaron

**Comment by reuvenpo** [comment]
Oh alright, i see. Thanks :)
