### ISSUE TITLE
Unable to set wacom area

### ISSUE THREAD

**Issue by TheFibix** [linuxwacom/input-wacom#88]
I am trying to set the wacom area to a specific set of values i used to use when I was on windows, but when trying to set the tablet area it doesn't let me, when trying to get the parameters i get this: 

> 

Property 'Wacom Tablet Area' does not exist on device.
xsetwacom set "16" "Button" "1" "button +1 "
xsetwacom set "16" "Button" "2" "button +2 "
xsetwacom set "16" "Button" "3" "button +3 "
xsetwacom set "16" "Button" "8" "button +8 "
xsetwacom set "16" "ToolDebugLevel" "0"
xsetwacom set "16" "TabletDebugLevel" "0"
xsetwacom set "16" "Suppress" "2"
xsetwacom set "16" "RawSample" "4"
Property 'Wacom Pressurecurve' does not exist on device.
xsetwacom set "16" "Mode" "Absolute"
Property 'Wacom Hover Click' does not exist on device.
xsetwacom set "16" "Touch" "on"
Property 'Wacom Hardware Touch Switch' does not exist on device.
xsetwacom set "16" "Gesture" "off"
xsetwacom set "16" "ZoomDistance" "0"
xsetwacom set "16" "ScrollDistance" "0"
xsetwacom set "16" "TapTime" "250"
Property 'Wacom Proximity Threshold' does not exist on device.
Property 'Wacom Rotation' does not exist on device.
xsetwacom set "16" "RelWheelUp" "1" "button +90 -90 "
xsetwacom set "16" "RelWheelDown" "2" "button +91 -91 "
xsetwacom set "16" "AbsWheelUp" "3" "button +90 -90 "
xsetwacom set "16" "AbsWheelDown" "4" "button +91 -91 "
xsetwacom set "16" "AbsWheel2Up" "5" "button +92 -92 "
xsetwacom set "16" "AbsWheel2Down" "6" "button +93 -93 "
xsetwacom set "16" "StripLeftUp" "1" "button +94 -94 "
xsetwacom set "16" "StripLeftDown" "2" "button +95 -95 "
xsetwacom set "16" "StripRightUp" "3" "button +96 -96 "
xsetwacom set "16" "StripRightDown" "4" "button +97 -97 "
xsetwacom set "16" "Threshold" "0"
xsetwacom set "16" "BindToSerial" "0"
Property 'Wacom Pressure Recalibration' does not exist on device.
xsetwacom set "16" "PanScrollThreshold" "13" 

> 

Note how it says Wacom Tablet Area does not exist on this device.

Any suggestions?

**Comment by jigpu** [comment]
Based on the output, I'm going to assume that you're trying to set the area on a "pad" device. The "pad" device only represents the buttons and other controls on the tablet and so don't have an area property that can be modified. If you want to set a custom area, you'll need to set it for the "stylus" and "eraser" devices.
